### ISSUE TITLE
Ethereum wallet

### ISSUE THREAD

**Issue by chainz06** [WalletConnect/walletconnect-registry#10]
## App Logo (Required)
(Attach image here)

## App Details (Required)
Type: Wallet or Dapp
Name:
Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Empty submission
