### ISSUE TITLE
AirGap Wallet

### ISSUE THREAD

**Issue by MrSlinkyman** [WalletConnect/walletconnect-registry#108]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/3213052/118733695-9cc3a180-b7f1-11eb-9ffb-0a98df76b94e.png)

## App Details (Required)
Type: Wallet
Name: AirGap Wallet
Homepage Url: https://airgap.it/
Chains supported: AE
AGI
AION
AMPL
ANT
AOA
ATOM
BAL
BAND
BAT
BNB
BRC
BTC
BTM
BUSD
CEL
CENNZ
CHSB
CHZ
COMP
CRO
CRV
CUSDC
CVT
DAI
DOT
DX
ELF
ENG
ENJ
ETH
FET
FTM
GNT
GRS
HEDG
HOT
HT
HUSD
INB
INO
INS
IOST
IOTX
KCS
KNC
KSM
LEND
LEO
LINK
LPT
LRC
MANA
MATIC
MCO
MKR
MLN
MXC
NEXO
NMR
NXM
OCEAN
OKB
OMG
PAX
PNK
QNT
REN
REV
RLC
RSR
SAI
SNX
SRM
STAKE
STORJ
SXP
THETA
TRAC
TRB
TUSD
UBT
UMA
USDC
USDT
USDTZ
UTK
WBTC
WNXM
XCHF
XIN
XTZ
YFI
ZB
ZIL
ZRX

## App Url (Required - at least one)
Browser Url: https://airgap.it/
iOS Url: https://itunes.apple.com/us/app/airgap-wallet/id1420996542?l=de&ls=1&mt=8
Android Url: https://play.google.com/store/apps/details?id=it.airgap.wallet https://github.com/airgap-it/airgap-wallet/releases
Mac Url: https://github.com/airgap-it/airgap-wallet/releases
Windows Url: https://github.com/airgap-it/airgap-wallet/releases
Linux Url: https://github.com/airgap-it/airgap-wallet/releases

## Mobile Linking (Optional)
Deep Link: 
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Since when does AirGap support WalletConnect if they've created their own protocol for interoperating with wallets???? cc @MrSlinkyman
