### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by chainz06** [WalletConnect/walletconnect-registry#11]
## App Logo (Required)
(Attach imag
![Screenshot_2021-03-31-01-24-06](https://user-images.githubusercontent.com/81656125/113064643-1363fb80-91c0-11eb-9d26-6bbd41cd51ec.png)
e here)

## App Details (Required)
Type: Wallet or Dapp
Name:
Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Invalid submission
