### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by JianBinWu** [WalletConnect/walletconnect-registry#110]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/20766533/118768538-b5938c00-b8b1-11eb-8f96-8241e10fc7ec.png)

## App Details (Required)
Type: Wallet
Name: DPToken
Homepage Url: https://dplatform.io/#plans
Chains supported: ETH, BTC, DOM

## App Url (Required - at least one)
iOS Url: https://dplatform.io/#plans

## Mobile Linking (Optional)
Universal Link: https://scan-testnet.domchain.io

**Comment by JianBinWu** [comment]
Is there any problem with the content we submitted? If there is a problem, please let us know and we will fix it.

**Comment by chadyj** [comment]
Hey @JianBinWu Thanks for your submission.
The logo is not available. Can you please resubmit with an available logo?
