### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by Nick-1979** [WalletConnect/walletconnect-registry#111]
## App Logo (Required)
https://www.ibit.exchange/images/favico.png

## App Details (Required)
Type:  Dapp
Name: ibit exchange
Homepage Url:www.ibit.exchange/idex
Chains supported: mainnet, rinkeby

## App Url (Required - at least one)
Browser Url:https://www.ibit.exchange/idex
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
@Nick-1979 Thanks for the submission.
Can you please resubmit with a bigger logo? 400x400.
