### ISSUE TITLE
New App Submission - Axion

### ISSUE THREAD

**Issue by JTravaux** [WalletConnect/walletconnect-registry#112]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/30296275/118982232-38b3f100-b949-11eb-87aa-e5c775bcd145.png)
https://stake.axion.network/logo.png

## App Details (Required)
Type: **Dapp**
Name: **Axion**
Homepage Url: **https://stake.axion.network**
Chains supported: **Ethereum**

## App Url (Required - at least one)
Browser Url: **https://stake.axion.network**

## Metadata (Optional)
Short Name:
Primary Color: **#176ebf**
Secondary Color: **#0faad6**

**Comment by pedrouid** [comment]
Added on commit ed6a5a53a0718cc7d0713b8ba9190c1281b68adc
