### ISSUE TITLE
Signal custom chains in wallets.json

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-registry#116]
currently there is a field "chains" - but as far as I see you can only signal concrete chains here. IMHO it would be good to be able to signal that a wallet supports custom chains. 
Maybe a boolean field "supportsCustomChains"?

**Comment by pedrouid** [comment]
I see what you mean but more important now for the registry to focus on getting a good grasp of chain support on WalletConnect ecosystem

Besides WalletConnect v2.0 will be able to communicate this compatibility in-protocol.

If a wallet supports `wallet_addEthereumChain` then the compatibility will be agreed upon connection on the JSON-RPC api methods.
