### ISSUE TITLE
Offer f-droid link

### ISSUE THREAD

**Issue by ligi** [WalletConnect/walletconnect-registry#118]
currently "android" always links to play. But it should also be able to link to f-droid. Not yet sure how to do that nicely in a backward compatible way.

Ideally it would be something like:

```json
{
"android": { "play": "https://play.google.com/foo"  , "f-droid": "https://f-droid.org/en/packages/org.walleth" }
}
```
this way it would also be open to stores like the amazon one

**Comment by chadyj** [comment]
Thanks for the suggestion @ligi!

F-droid links are now part of the new cloud registry :+1:
