### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by chainz06** [WalletConnect/walletconnect-registry#12]
# App Logo (Required)
(Attach image here)
![IMG_20210331_013129_838](https://user-images.githubusercontent.com/81656125/113065463-9e91c100-91c1-11eb-914c-19b90ebe7e90.JPG)

## App Details (Required)
Type: Wallet
Name: Ethereum Wallet
Homepage Url:https://freewallet.org/
Chains supported:

## App Url (Required - at least one)https://freewallet.org/
Browser Url:https://freewallet.org/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:
@

**Comment by pedrouid** [comment]
Why does the logo look so different from the website? Also I can't see any mentions of WalletConnect?? Do you represent the team in any form?

**Comment by chainz06** [comment]
No I don't.

But I can kindly say that I got my problem fixed, thank you for caring
@Pedro
