### ISSUE TITLE
New App Submission(CoinUs)

### ISSUE THREAD

**Issue by coinus** [WalletConnect/walletconnect-registry#120]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/38288958/119325258-ae0e2180-bcbb-11eb-8385-9dd3b8275c78.png)

## App Details (Required)
Type: APP Wallet
Name: CoinUs
Homepage Url: https://www.coinus.io/
Chains supported: BTC, ETH (ERC20), RVN (RVN Assets), Filecoin

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/kr/app/coinus-wallet/id1367339746
Android Url: https://play.google.com/store/apps/details?id=com.theblockchain.coinus.wallet&hl=en&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
@coinus Thanks for the submission.
The app logo is 404. Can you please update and re-submit?

**Comment by coinus** [comment]
@chadyj 
The initial application was closed and you've mentioned about logo 404. I'm not sure what you mean by 404 for the image.
If you click the image the link works. Can you please check again?

**Comment by chadyj** [comment]
@coinus All good now. I checked during a recent Github outage 🤦

**Comment by Andrewbono** [comment]
Thank you! Please let us know once its registered :)

**Comment by coinus** [comment]
@chadyj 
can we get a estimated timeline when our wallet be update?

**Comment by pedrouid** [comment]
Added on commit 3f65bc82febfff9dc6ae5658005312857276fe34
