### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by kaguamaru** [WalletConnect/walletconnect-registry#123]
## App Logo (Required)
(Attach image here)

## App Details (Required)
Type: Wallet or Dapp
Name: Marco wallet

Homepage Url: metamask.io
Chains supported:
0xe33d2C1223A025c8B89d4C12eC09Bb951E6f4D91

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
This issue will be closed since required content is missing.
