### ISSUE TITLE
New App Submission - PlotX

### ISSUE THREAD

**Issue by ankitnirwal** [WalletConnect/walletconnect-registry#124]
## App Logo (Required)
![PlotX-bg-favicon](https://user-images.githubusercontent.com/61899399/119740706-fedf6f00-bea1-11eb-8ca9-4b191071ab02.png)

## App Details (Required)
Type: Dapp
Name:PlotX
Homepage Url:app.plotx.io
Chains supported:137

## App Url (Required - at least one)
Browser Url:app.plotx.io

**Comment by pedrouid** [comment]
Added on commit 0182f0cbe2f7128fcc69fdad69eb4cce00a46a0e
