### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by danblex01** [WalletConnect/walletconnect-registry#125]
## App Logo (Required)

blob:file:///d3c3a011-6ab4-4307-81dd-93da1febf4ee

## App Details (Required)
Type: Wallet or Dapp
Name: Trustwallet
Homepage Url: www.trustwallet.com

## App Url (Required - at least one)
Browser Url: https://trustwallet.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Col

**Comment by chadyj** [comment]
Trust Wallet is already featured in the registry.
