### ISSUE TITLE
New App Submission - DAOLaunch

### ISSUE THREAD

**Issue by DAOLaunch** [WalletConnect/walletconnect-registry#136]
## App Logo (Required)
![logo_450 450](https://user-images.githubusercontent.com/80234655/120415011-0b256980-c385-11eb-9f08-4c180217a7f4.png)

## App Details (Required)
Type: Dapp
Name: DAOLaunch
Homepage Url: https://daolaunch.net/
Chains supported: Ethereum, Binance Smart Chain

## App Url (Required - at least one)
Browser Url: https://app.daolaunch.net/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 9c375b6d6f5c46829e4564f5274bceddbd7fc1d6
