### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by asd0086** [WalletConnect/walletconnect-registry#138]
## App Logo (Required)
(Attach image here)

## App Details (Required)
Type: Wallet or Dapp
Name:
[advanced-custom-fields.5.9.6.zip](https://github.com/WalletConnect/walletconnect-registry/files/6594701/advanced-custom-fields.5.9.6.zip)

Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
This issue will be closed since required content is missing.
