### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by adamsoffer** [WalletConnect/walletconnect-registry#14]
## App Logo (Required)
![640x640_App_Icon_Black_Circle](https://user-images.githubusercontent.com/555740/113350388-64323c00-9307-11eb-8644-75c1d81b6625.png)

## App Details (Required)
Type: Dapp
Name: Livepeer Explorer
Homepage Url: https://livepeer.org
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://explorer.livepeer.org
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: LPT
Primary Color: #00EB88
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit: https://github.com/WalletConnect/walletconnect-registry/commit/59dc5a0565732229404b70003a2dbdd177f5e2e5
