### ISSUE TITLE
New App Submission - Gnosis

### ISSUE THREAD

**Issue by sche** [WalletConnect/walletconnect-registry#140]
## App Logo (Required)
![gnosis_safe_logo](https://user-images.githubusercontent.com/2284385/120831225-9eb29200-c55f-11eb-9ec0-689759e022e8.png)

## App Details (Required)
Type: Wallet
Name: Gnosis Safe
Homepage Url: https://gnosis-safe.io/
Chains supported: mainnet, rinkeby (other L2 chains coming soon)

## App Url (Required - at least one)
Browser Url: https://gnosis-safe.io/app/
iOS Url: https://apps.apple.com/app/id1515759131
Android Url: https://play.google.com/store/apps/details?id=io.gnosis.safe
Mac Url: no
Windows Url: no
Linux Url: no

## Mobile Linking (Optional)
Deep Link: gnosissafe
Universal Link: gnosis-safe.io

## Desktop Linking (Optional)
Deep Link: no
Universal Link: no

## Metadata (Optional)
Short Name: Gnosis Safe
Primary Color: 
Secondary Color:

**Comment by pedrouid** [comment]
Updated on commit 6feb37768a181c35f5806cf277969e54c3bc9aba
