### ISSUE TITLE
New App Submission - B.Protocol

### ISSUE THREAD

**Issue by Katchka** [WalletConnect/walletconnect-registry#145]
## App Logo (Required)
https://drive.google.com/file/d/1__SsSjWVdkAdOD1OE9BIvM1Fg9zC097z/view?usp=sharing

## App Details (Required)
Type: Dapp
Name: B.Protocol
Homepage Url: https://bprotocol.org
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://app.bprotocol.org/app
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by Katchka** [comment]
Any ETA on this one to be merged and B.Protocol to be added to - https://registry.walletconnect.org/apps 

Thanks

**Comment by pedrouid** [comment]
Added on commit ec591d0de2c3bc0bc5dd9957e5ad64d6ef06ce82
