### ISSUE TITLE
Exodus

### ISSUE THREAD

**Issue by prosper25** [WalletConnect/walletconnect-registry#15]
## App Logo (Required)
(Attach image here)

## App Details (Required)
Type: Wallet or Dapp
Name: Exodus Wallet
Homepage Url: https://www.exodus.com
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Logo missing and App url... also can you confirm that Exodus supports WalletConnect and you represent their team in any form?
