### ISSUE TITLE
New App Submission - Celo Wallet

### ISSUE THREAD

**Issue by jmrossy** [WalletConnect/walletconnect-registry#155]
## App Logo (Required)
![icon](https://user-images.githubusercontent.com/710751/121215413-f85fd880-c84d-11eb-9c7b-e4becd793f19.png)

## App Details (Required)
Type: Wallet
Name: Celo Wallet
Homepage Url: https://celowallet.app
Chains supported: Celo

## App Url (Required - at least one)
Browser Url: https://celowallet.app
iOS Url:
Android Url:
Mac Url: https://celowallet.app
Windows Url: https://celowallet.app
Linux Url: https://celowallet.app

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link: celowallet://wc?uri={ENCODED_WALLETCONNECT_URI}
Universal Link:

## Metadata (Optional)
Short Name: Celo Wallet
Primary Color: #35D07F
Secondary Color: #FBCC5C

**Comment by pedrouid** [comment]
Added on commit 99a39c39eedcab66b80602426cba7526ee945de7
