### ISSUE TITLE
New App Submission (Flexa)

### ISSUE THREAD

**Issue by kaw182** [WalletConnect/walletconnect-registry#176]
## App Logo (Required)
![Flexa Icon - Red](https://user-images.githubusercontent.com/78556774/122278019-211a4a80-ceac-11eb-8985-3ea92c38d8f7.png)

## App Details (Required)
Type: Wallet or Dapp
Name: Flexa
Homepage Url: https://app.flexa.network/
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://app.flexa.network/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 7959fa5ad51ac81791e238b06b4731ec422b3e90
