### ISSUE TITLE
New App Submission: Minerva Wallet

### ISSUE THREAD

**Issue by PeterTheOne** [WalletConnect/walletconnect-registry#184]
## App Logo (Required)
https://minerva.digital/i/minerva-owl.svg

## App Details (Required)
Type: Wallet
Name: Minerva Wallet
Homepage Url: https://minerva.digital/
Chains supported: ARTIS sigma1,  xDai Chain, Ethereum, POA Core, (soon Matic PoS Chain and more).
Test Chains supported: ARTIS tau1, Rinkeby, POA Sokol, LUKSO (L14 Testnet), Kovan, Görli, Ropsten, (soon: Mumbai and more)

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=digital.minerva
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Minerva
Primary Color: #443ad2
Secondary Color:

**Comment by PeterTheOne** [comment]
@pedrouid plz review and have a nice day :)

**Comment by pedrouid** [comment]
Added on commit 9dfdd8158475656fb8e9d9b8f476c80906f44e61

**Comment by PeterTheOne** [comment]
Some fixes and additions https://github.com/WalletConnect/walletconnect-registry/pull/351
