### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by doananh234** [WalletConnect/walletconnect-registry#185]
## App Logo (Required)
![logo](https://user-images.githubusercontent.com/23400269/122944938-69e96c00-d3a2-11eb-9bfe-2dc8fc45676b.png)

## App Details (Required)
Type: Dapp
Name: Twinci
Homepage Url: https://twinci.io
Chains supported: Binance Smart Chain Mainnet (56), Binance Smart Chain Testnet (97)

## App Url (Required - at least one)
Browser Url: https://app.twinci.io
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Twinci
Primary Color: #a3b85a
Secondary Color: #f0a61f

**Comment by hungbang** [comment]
@pedrouid 
Could you help us to take a look at this request, please? We are developing an NFT marketplace, at the moment, we had > 7000 users, > 5000 NFTs, >3000 transactions. I know it's not a big impression, but we are growing fast. We hope that wallet connect can give our users much more experience. We're looking forward to hearing from you soon. Let us know if you have any questions. 

Thank you and regards. 

Harry From Twinci.

**Comment by pedrouid** [comment]
Added on commit ae7b6448ce48779f5bc0aeccd686696f5d034174
