### ISSUE TITLE
New App Submission - ArchiPage (Wallet)

### ISSUE THREAD

**Issue by gruming** [WalletConnect/walletconnect-registry#187]
## App Logo (Required)
<img width="1024" alt="AP_Appicon" src="https://user-images.githubusercontent.com/10935758/123022789-44477b80-d411-11eb-9c65-3efb44151e1b.png">

## App Details (Required)
Type: Wallet
Name: ArchiPage
Homepage Url: [https://www.criptoarchi.com/](https://www.criptoarchi.com/)
Chains supported: Ethereum Mainnet

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url: [https://play.google.com/store/apps/details?id=com.archipage](https://play.google.com/store/apps/details?id=com.archipage)
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: archipage://wc
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: ArchiPage
Primary Color: #000000
Secondary Color: #FFFFFF

**Comment by pedrouid** [comment]
Added on commit 1990fe28688d6f9f848f766971da1894c9615c02
