### ISSUE TITLE
New App Submission - Cripto Archi Finance (Dapp)

### ISSUE THREAD

**Issue by gruming** [WalletConnect/walletconnect-registry#188]
## App Logo (Required)
<img width="1024" alt="CA_Logo" src="https://user-images.githubusercontent.com/10935758/123037698-09057680-d42a-11eb-8a2d-a94797abff2a.png">

## App Details (Required)
Type: Dapp
Name: Cripto Archi Finance
Homepage Url: [https://www.criptoarchi.com](https://www.criptoarchi.com)
Chains supported:

## App Url (Required - at least one)
Browser Url: [https://www.criptoarchi.finance](https://www.criptoarchi.finance)
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Cripto Archi Finance
Primary Color: #5A56E9
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 6d4bbf71446209919cb4bfc359f4b61e77aa1c7d
