### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by Haso-ux** [WalletConnect/walletconnect-registry#189]
## App Logo (Req[Paypal ](www.paypal.com) uired)
(Attach image here)

## App Details (Required)
Type: Wallet or Dapp
Name:
Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by TN8ru5omyg2kf94j6SH7DyEENPJkFY2ftZ** [comment]
Abc
