### ISSUE TITLE
New App Submission - cmorq

### ISSUE THREAD

**Issue by SomeMoosery** [WalletConnect/walletconnect-registry#19]
## App Logo (Required)

https://storage.googleapis.com/asset_logos/cmorq-logo.png

![cmorq-logo](https://user-images.githubusercontent.com/15767602/114115166-50ab4600-98b0-11eb-975f-450367206864.png)

## App Details (Required)
Type: Dapp
Name: cmorq
Homepage Url: https://cmorq.com
Chains supported: Ethereum, Bitcoin

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/ke/app/cmorq/id1530022030
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 7048a41
