### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by julia-ihnatova** [WalletConnect/walletconnect-registry#191]
## App Details (Required)![Moonkat](https://user-images.githubusercontent.com/6807962/123542749-0077ad80-d754-11eb-8a8d-19ebd3f0f8d3.png)Type: Wallet or Dapp
[Name:] Moonkat https://moonkat.net/ 
Homepage Url: https://moonkat.net/
Chains supported: BSC mainnet

## App Url (Required - at least one)
Browser Url: https://moonkat.net/dashboard
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit bb8b365e5c6818d7959d862b9d486a26a919efa1
