### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by 0xViktor** [WalletConnect/walletconnect-registry#192]
## App Logo (Required)
![logo-punk-512](https://user-images.githubusercontent.com/83581265/123577084-23669800-d80e-11eb-87e0-e75caf864360.png)

## App Details (Required)
Type: Dapp
Name: Punk Protocol
Homepage Url: [https://punk.finance](https://punk.finance)
Chains supported: Ethereum(ETH)

## App Url (Required - at least one)
Browser Url: [https://app.punk.finance](https://app.punk.finance)
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 93d4d51e8471154afe2b3dcffed3bda07760f4cd
