### ISSUE TITLE
New App Submission - Himegami Protocol

### ISSUE THREAD

**Issue by thanh-solashi** [WalletConnect/walletconnect-registry#193]
## App Logo (Required)
![himegami1_haikei ed064bab](https://user-images.githubusercontent.com/49665448/123621324-48bacc80-d835-11eb-86fb-277be18ea023.png)

## App Details (Required)
Type: Dapp
Name: Himegami Protocol
Homepage Url: https://himegamiprotocol.org/
Chains supported: 1 (Ethereum mainnet)

## App Url (Required - at least one)
Browser Url: https://himegamiprotocol.org/

**Comment by pedrouid** [comment]
Added on commit af91999a22ea398e7fa6f3c58c3c23b4a09b9ddf
