### ISSUE TITLE
New App Submission - Tangem

### ISSUE THREAD

**Issue by Andoran90** [WalletConnect/walletconnect-registry#208]
## App Logo (Required)
![Tangem_app](https://user-images.githubusercontent.com/24321494/124071202-72a00900-da58-11eb-935a-dcdab21de52b.png)

## App Details (Required)
Type: Wallet
Name: Tangem
Homepage Url: https://tangem.com
Chains supported: ETH

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/uz/app/tangem/id1354868448
Android Url: https://play.google.com/store/apps/details?id=com.tangem.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: tangem:
Universal Link: https://app.tangem.com

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Tangem
Primary Color:
Secondary Color:

**Comment by Andoran90** [comment]
@pedrouid 
Can you please take a look this app submission and if everything is OK add this app to WalletConnect registry

Andrew from Tangem

**Comment by pedrouid** [comment]
Added on commit 50446038485721a4a74a99df695ce967e1a2bbf8
