### ISSUE TITLE
New App Submission - GhostMarket

### ISSUE THREAD

**Issue by vincentgeneste** [WalletConnect/walletconnect-registry#211]
## App Logo (Required)
![Logo](https://user-images.githubusercontent.com/25534589/128311593-2a1877b2-2d0d-4c54-88ab-5a0044182701.png)

## App Details (Required)
Type: Dapp
Name: GhostMarket
Homepage Url: https://ghostmarket.io
Chains supported: BSC, Ethereum, Polygon, Avalanche, Neo N3

## App Url (Required - at least one)
Browser Url: https://ghostmarket.io
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: GhostMarket
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 50446038485721a4a74a99df695ce967e1a2bbf8
