### ISSUE TITLE
New App Submission - Defii Wallet

### ISSUE THREAD

**Issue by toan88291** [WalletConnect/walletconnect-registry#213]
App Logo 
![img](https://firebasestorage.googleapis.com/v0/b/defii-c10c7.appspot.com/o/logo.png?alt=media&token=e0ee70a2-00a7-4e4e-92ac-6d2ad3d74ceb)

## App Details (Required)
Type: Wallet
Name: Defii 
Homepage Url: https://defii.app/
Chains supported: Ethereum , Binance Smart Chain .

## App Url (Required - at least one)
Browser Url: 
iOS Url: https://apps.apple.com/vn/app/defii/id1561955575
Android Url: https://play.google.com/store/apps/details?id=io.defii
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: defii://
Universal Link: https://defii.app/

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Defii
Primary Color: #FCB751
Secondary Color: #E84615

**Comment by toanagiletech** [comment]
@pedrouid

**Comment by pedrouid** [comment]
Is the app still maintained?

**Comment by pedrouid** [comment]
Added on commit a4a23c37fb09fb182d5c5c21727d2890e2820cc1
