### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by guoxiaopang** [WalletConnect/walletconnect-registry#214]
## App Logo (Required)
![Icon-App-1024x1024](https://user-images.githubusercontent.com/11028035/124534030-06e9e180-de46-11eb-8154-ed3091b000c1.png)

## App Details (Required)
Type: Wallet 
Name: ioPay
Homepage Url: https://iopay-wallet.iotex.io/
Chains supported:  ["eip155:4689, eip155:4690"]

## App Url (Required - at least one)
Browser Url: https://iopay-wallet.iotex.io/
iOS Url:  https://apps.apple.com/app/apple-store/id1478086371
Android Url:  https://play.google.com/store/apps/details?id=io.iotex.iopay.gp
Mac Url: https://github.com/iotexproject/iotex-explorer/releases
Windows Url: https://github.com/iotexproject/iotex-explorer/releases
Linux Url: https://github.com/iotexproject/iotex-explorer/releases

##Mobile Linking (Optional)
Universal Link: https://member.iotex.io/

**Comment by guoxiaopang** [comment]
@pedrouid

**Comment by pedrouid** [comment]
Added on commit 480c8f7dd7158cd9e638b22e9bef82719b23a8a5

**Comment by anshuomomo** [comment]
Hi @pedrouid , I have met a problem,  when i want to connect wallet in a dapp, why does our ioPay wallet not in the showing registry list? Could you give some help or some informations for this? How could our wallet show in the connect list?
