### ISSUE TITLE
New APP Submission - Coinhub （Wallet）

### ISSUE THREAD

**Issue by GooSatoru** [WalletConnect/walletconnect-registry#215]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/79819313/125082136-6d4a5a80-e0f9-11eb-8eb2-cc68560b1364.png)
![image](https://user-images.githubusercontent.com/79819313/125083010-6ff97f80-e0fa-11eb-8acf-dcd9303a5875.png)
![image](https://user-images.githubusercontent.com/79819313/125082934-6112cd00-e0fa-11eb-950c-b0142bad527c.png)
![image](https://user-images.githubusercontent.com/79819313/125082870-4dfffd00-e0fa-11eb-9f32-f91a927a7b27.png)

## App Details (Required)
Type: Wallet
Name: Coinhub
Homepage Url: https://coinhub.org
Chains supported: Ethereum, Heco Chain, Binance Smart Chain, OKExChain, Hoo Smart Chain, Ploygon Network

## App Url (Required - at least one)
Browser Url: https://coinhub.org/download
iOS Url:  https://apps.apple.com/tn/app/coinhub/id1567786851
Android Url: https://static.coinhub.org/package/Coinhub_v1.2.0.apk
Mac Url: 
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: 
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Coinhub
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
added on commit 1ddf64495ccfd7fdfbc866d8caebe14d57845557
