### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by dysquard** [WalletConnect/walletconnect-registry#218]
## App Logo (Required)
![logo](https://user-images.githubusercontent.com/16001323/125748324-dbb7c359-931d-42ed-af8f-b331c9f2e5aa.png)

## App Details (Required)
Type: Wallet
Name: Go Pocket
Homepage Url: https://gopocket.finance
Chains supported: Ethereum, Polygon, Arbitrum, BSC, HECO(not yet)

## App Url (Required - at least one)
iOS Url: https://testflight.apple.com/join/KoUa5pBP
Android Url: https://play.google.com/store/apps/details?id=io.gopocket

**Comment by dysquard** [comment]
Well, respond is a little bit slow...

**Comment by pedrouid** [comment]
Added on commit 63a809a4d2f1851c33cec14bc757afff82e4af6a

**Comment by dysquard** [comment]
Hi thx for your respond!

And I'd like to update some info for Go Pocket.

"mobile": {
    "native": "gopocket:",
    "universal": "https://gopocket.security/"
  },
  "desktop": {
    "native": "",
    "universal": ""
  },
  "metadata": {
    "shortName": "Go Pocket",
    "colors": {
      "primary": "rgb(255, 255, 255)",
      "secondary": ""
    }
  }
