### ISSUE TITLE
WalletConnect Call Sign Issue

### ISSUE THREAD

**Issue by SafePalWallet** [WalletConnect/walletconnect-registry#220]
I use iPhone Safari to open https://example.walletconnect.org and use SafePal to link the wallet through WalletConnect. Everything is normal. Then I click the person_sign button in Safari, it will directly open the AppStore and be redirected to Rainbow Wallet. Through the browser’s local storage, I found that the value saved by WALLETCONNECT_DEEPLINK_CHOICE is {"name":"Rainbow","href":"https://rnbwapp.com/wc"}. Obviously this is wrong data. I don’t know if I change it. How to fix this problem, I look forward to your reply, thank you!

The SafePal mobile gegistry https://github.com/WalletConnect/walletconnect-monorepo/blob/1.3.6/packages/helpers/mobile-registry/registry.json. Also, the LOGO has been updated in this submission. If I want to display the new LOGO on WalletConnect, what do I need to do?

**Comment by pedrouid** [comment]
This seems related to this PR https://github.com/WalletConnect/walletconnect-monorepo/pull/544
