### ISSUE TITLE
New App Submission YFX

### ISSUE THREAD

**Issue by Pedro137BR** [WalletConnect/walletconnect-registry#223]
## App Logo (Required)
(Attach image here)
![YFXLogo](https://user-images.githubusercontent.com/41971106/126051030-d2a141e1-960a-4f86-adbe-19e336bc8266.png)

## App Details (Required)
Type: Dapp
Name: YFX - Your Future Exchange
Homepage Url: https://www.yfx.com/
Chains supported: ETH, BSC, Tron, Heco, OKEx

## App Url (Required - at least one)
Browser Url: https://www.yfx.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 182b84fa103f98e7126b92cb6f6b28523e2e5998
