### ISSUE TITLE
New App Submission - yiToken (Wallet)

### ISSUE THREAD

**Issue by mekery** [WalletConnect/walletconnect-registry#224]
## App Logo (Required)
![yiToken-logo-rounded-48](https://user-images.githubusercontent.com/1023474/126100136-352089fa-f758-4654-8719-02e6700cfc0b.png)
![yiToken-logo-rounded-64](https://user-images.githubusercontent.com/1023474/126100142-f4358a65-da77-4676-bfec-d59720a9c96a.png)
![yiToken-logo-rounded-128](https://user-images.githubusercontent.com/1023474/126100160-3e8eedb9-77af-4101-8ecc-c7955f9b571f.png)
![yiToken-logo-rounded-512](https://user-images.githubusercontent.com/1023474/126100167-3c49ee8b-e8ff-47aa-a4d8-f819efd5e9c1.png)

## App Details (Required)
Type: Wallet
Name: yiToken
Homepage Url: https://yitoken.im
Chains supported: Bitcoin, Ethereum, Heco, BSC, Cosmos, OKExChain, ClassZZ, Polkadot, Kusama, Solana, Polygon, Avalanche

## App Url (Required - at least one)
Browser Url: https://yitoken.im
iOS Url: https://testflight.apple.com/join/vwyDi2pn
Android Url: https://app.iwishbest.com/apps/yiToken.apk
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: yitoken:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: yiToken
Primary Color: rgb(44, 76, 252)
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit a027794645f6250c6618d1d2dc472bab2a7a5ffa
