### ISSUE TITLE
Trust wallet

### ISSUE THREAD

**Issue by Kaito16-sea** [WalletConnect/walletconnect-registry#227]
## App Logo (Required)
(Attach image here)
![images](https://user-images.githubusercontent.com/80135665/127365265-ce55b1c5-f66c-4713-9987-1a39987d6e76.png)

## App Details (Required)
Type: Wallet or Dapp
Name:
Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by Minhaz55** [comment]
Awesome
