### ISSUE TITLE
New App Submission (Vesper Finance)

### ISSUE THREAD

**Issue by michaelmcquaid** [WalletConnect/walletconnect-registry#230]
## App Logo (Required)

<img width="1200" alt="Vesper-2021-Token-RGB@2x" src="https://user-images.githubusercontent.com/79603900/127370616-4d62f1fe-9a2b-4d46-aa83-7beed59022bc.png">

## App Details (Required)
Type:  Dapp
Name:  Vesper Finance
Homepage Url:  https://vesper.finance/
Chains supported:  ETH

## App Url (Required - at least one)
Browser Url:   https://app.vesper.finance/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

Vesper is looking to be listed on your App registry.  Thank you!

**Comment by pedrouid** [comment]
Added on commit d56ea52a7e1444f122935ef459f1f1e80c0f8f10
