### ISSUE TITLE
Wont connect

### ISSUE THREAD

**Issue by Sweezey22** [WalletConnect/walletconnect-registry#236]
My wallet connect wont connect to trust wallet on various sites from browser. I have I phone and  also various transactions wont go through its hard to buy or sell anything

**Comment by Jerrryrybon** [comment]
> My wallet connect wont connect to trust wallet on various sites from browser. I have I phone and  also various transactions wont go through its hard to buy or sell anything

You need to contact Trust Wallet support team directly. Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by Sweezey22** [comment]
It’s asking me for my recovery phrase. I’m not giving my wallet access information over. My bank doesn’t ask me for my password with an issue so why is trust wallet
