### ISSUE TITLE
New Wallet Submission (fuse.cash)

### ISSUE THREAD

**Issue by leonprou** [WalletConnect/walletconnect-registry#239]
## App Logo (Required)
![fuse_cash](https://user-images.githubusercontent.com/7228844/129472745-83ddedcf-efb8-4867-a7c0-7df9e2ea788c.png)

## App Details (Required)
Type: Wallet
Name: fuse.cash
Homepage Url: https://fuse.cash/
Chains supported: Fuse Network

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/fuse-cash/id1559937899
Android Url: https://play.google.com/store/apps/details?id=io.fuse.cash
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: fuse.cash://
Universal Link: https://app.fuse.cash/

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: fuse.cash
Primary Color: `#37D888`
Secondary Color: `#FFFFFF`

**Comment by pedrouid** [comment]
Added on commit 25a9a36974ad419245d1c16d65c56677babcc227
