### ISSUE TITLE
New App Submission - Elastos Essentials

### ISSUE THREAD

**Issue by BenjaminPiette** [WalletConnect/walletconnect-registry#241]
## App Logo (Required)
![Elastos_Essentials_icon_rounded](https://user-images.githubusercontent.com/7567594/129507626-babb2a94-741b-4905-bcf7-370959be622d.png)

## App Details (Required)
Type: Wallet
Name: Elastos Essentials
Homepage Url: https://www.elastos.org/
Chains supported: Elastos (chainid 20 (mainnet), 21 (testnet)) - More chains (eth, heco, bsc, fusion, ...) are under development

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/elastos-essentials/id1568931743
Android Url: https://play.google.com/store/apps/details?id=org.elastos.essentials.app
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: essentials:
Universal Link: https://essentials.elastos.net

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Essentials
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
added on commit 7adfb0965f9a02e727a79551234172cbff8c79b0
