### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by tuan-ps** [WalletConnect/walletconnect-registry#242]
## App Logo (Required)
![overlord_new_logo](https://user-images.githubusercontent.com/83691675/129538497-ed287494-d22a-4807-b60a-9447de418e14.png)

## App Details (Required)
Type: Wallet
Name: Overlord
Homepage Url: https://overlord.world/
Chains supported: ETH, BSC

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/vn/app/overlord-pvp-online-battle/id1528638606
Android Url: https://play.google.com/store/apps/details?id=com.nexgames.overlord&hl=en_US&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Is this a wallet or a dapp?
