### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by agent3bood** [WalletConnect/walletconnect-registry#243]
## App Logo (Required)
(Attach image here)
![whiteback](https://user-images.githubusercontent.com/771902/129607331-e7741b51-b606-4d55-b37c-ed70d3de2528.png)

## App Details (Required)
Type: Dapp
Name: NFTY Connect
Homepage Url: https://nftylabs.org
Chains supported: ETH, WAX

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/nfty-connect/id1580469680
Android Url: https://play.google.com/store/apps/details?id=org.nftylabs.nfty_connect
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: yes please
Universal Link: yes please

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: NFTY
Primary Color: #79088E
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit a54b07451416ad07a172253794b0cae472d75fe4
