### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by contxtsio-jetson** [WalletConnect/walletconnect-registry#251]
## App Logo (Required)
![nftbank-logo-round](https://user-images.githubusercontent.com/68371375/130250185-cefc317a-fd5b-421c-b4c1-213388a5780d.png)

## App Details (Required)
Type: Dapp
Name: NFTBank.ai
Homepage Url: https://nftbank.ai
Chains supported: Ethereum, Polygon, Ronin, Loom, Klaytn

## App Url (Required - at least one)
Browser Url: https://nftbank.ai
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: NFTBank.ai
Primary Color: #3B43FF
Secondary Color: #EF2A86

**Comment by pedrouid** [comment]
Added on commit 5a8587865fa5dd01ed293bb5cad2ab833c36be87
