### ISSUE TITLE
New App Submission - Feeds

### ISSUE THREAD

**Issue by stiartsly** [WalletConnect/walletconnect-registry#260]
## App Logo (Required)
![feeds-logo](https://user-images.githubusercontent.com/3350834/130928664-8a03610d-7f80-471f-b37f-8c79f97f590a.png)

## App Details (Required)
Type: Dapp
Name: Trinity Feeds 
Homepage Url: https://www.trinity-feeds.app/
Chains supported: Elastos Smart Contract Sidechain

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/trinity-feeds/id1546436333
Android Url: https://play.google.com/store/apps/details?id=io.trinitytech.dapp.feeds
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link: 
Universal Link:

## Metadata (Optional)
Short Name: Feeds
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit b9ba6b03b60cbc5942377806c7c66dda9f3d8a98
