### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by OldCrab** [WalletConnect/walletconnect-registry#267]
## App Logo (Required)
![изображение](https://user-images.githubusercontent.com/13282369/131745840-b90aab62-dad6-4af6-a9b5-026b7f1cd63f.png)

## App Details (Required)
Type: Wallet
Name: Stasis
Homepage Url: https://stasis.net
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: 
iOS Url: https://apps.apple.com/app/stasis-wallet/id1371949230
Android Url: https://play.google.com/store/apps/details?id=com.stasis.stasiswallet&hl=ru&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: stasis
Universal Link: https://app.stasis.net

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color: #2468E4
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 0f28aeee60cdc2fd5214868a0691327a44ccac34
