### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by bitpif** [WalletConnect/walletconnect-registry#268]
## App Logo (Required)
![logo200x200](https://user-images.githubusercontent.com/50061328/132095134-f0da0347-06b7-418d-bd82-c00b7050586e.png)

## App Details (Required)
Type: Dapp
Name: BITPIF
Homepage Url: https://bitpif.com/
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://bitpif.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link: https://bitpif.com/

## Desktop Linking (Optional)
Deep Link:
Universal Link: https://bitpif.com/

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit acb901a04ba401a0df54f59a117e48124bf38d21
