### ISSUE TITLE
Trustee Wallet (AppStore + Play Market)

### ISSUE THREAD

**Issue by taki-183** [WalletConnect/walletconnect-registry#27]
## App Logo (Required)
![720x720](https://user-images.githubusercontent.com/54359346/114548266-3682b680-9c68-11eb-89cb-538360496943.png)

## App Details (Required)
Type: Wallet
Name: Trustee Wallet
Homepage Url: https://trusteeglobal.com/
Chains supported: ERC20

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/trustee-wallet-bitcoin-wallet/id1462924276
Android Url: https://play.google.com/store/apps/details?id=com.trusteewallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit https://github.com/WalletConnect/walletconnect-registry/commit/3e58517d8ba43e0a9a06dd77b029afb4d98cd75b

**Comment by taki-183** [comment]
@pedrouid can you update our logo pls?
