### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by ionleahu** [WalletConnect/walletconnect-registry#272]
## App Logo (Required)
![logo](https://user-images.githubusercontent.com/57945408/132868131-16915183-c23d-4b4d-9e0d-3558ca65b44c.png)

## App Details (Required)
Type: Dapp
Name: IXSwap
Homepage Url: https://app.ixswap.io
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://app.ixswap.io
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: IXSwap
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
No WalletConnect support
