### ISSUE TITLE
JulWallet App Submission

### ISSUE THREAD

**Issue by AstonishGong** [WalletConnect/walletconnect-registry#281]
## App Logo (Required)
![Logo-Unicorn](https://user-images.githubusercontent.com/33471307/133489544-1732ff5b-d95c-4aa5-ae48-710fdb065369.png)

## App Details (Required)
Type: Wallet
Name: JulWallet
Homepage Url: https://justliquidity.org/
Chains supported: Fantom(250), ETH(1), BSC(56), Matic(137), Huobi ECO(128), Avalanche(43114), TomoChain(88), Ropsten(3), Kovan(42), Rinkeby(4), Goerli(5)

## App Url (Required - at least one)
Browser Url: https://chrome.google.com/webstore/detail/julwallet/fgkldlaelopgncepgpncndebgdddikii?hl=en-US
iOS Url: https://apps.apple.com/app/julwallet/id1555914591
Android Url: https://play.google.com/store/apps/details?id=julwallet.com
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: julwallet:
Universal Link: https://justliquidity.org/

## Desktop Linking (Optional)
Deep Link: 
Universal Link: 

## Metadata (Optional)
Short Name: "JulWallet"
Primary Color: `#c84ce4`
Secondary Color: `#3f00ff`

**Comment by pedrouid** [comment]
Added on commit 7675356d001b6b5eb7a9e8ddf5bee42c1517958c
