### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by starshiptoken** [WalletConnect/walletconnect-registry#282]
## App Logo (Required)
(Attach image here)
![SSLayer 1](https://user-images.githubusercontent.com/88906926/133466131-39fa51e2-93cf-49ce-bac1-05057a2cf32f.png)

## App Details (Required)
Type: Wallet
Name: StarBase 
Homepage Url: https://deploystarship.com
Chains supported: Ethereum (erc20), Binance (bep20/bep2)

## App Url: https://play.google.com/store/apps/details?id=com.starbase.wallet 
Browser Url: https://deploystarship.com
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=com.starbase.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
added on commit 27d0074034a487171750cd14b43f40c22fbdd793
