### ISSUE TITLE
Chainge Wallet Submission

### ISSUE THREAD

**Issue by RodeRickIsWatching** [WalletConnect/walletconnect-registry#283]
## App Logo (Required)
(Attach image here)
![https://chainge.oss-cn-hongkong.aliyuncs.com/public/chng256.png](https://chainge.oss-cn-hongkong.aliyuncs.com/public/chng256.png)

## App Details (Required)
Type: Wallet
Name: Chainge Finance
Homepage Url: [https://www.chainge.finance](https://www.chainge.finance)

Chains supported:
- Binance Smart Chain - 56
- Ethereum - 1
- Fusion - 32659
- Fantom - 250
- Heco - 128
- Polygon - 137
- OKex Chain - 66

## App Url 
Browser Url: 
iOS Url: [https://apps.apple.com/cn/app/id1578987516](https://apps.apple.com/cn/app/id1578987516)
Android Url: [https://play.google.com/store/apps/details?id=com.fusion.chainge.android](https://play.google.com/store/apps/details?id=com.fusion.chainge.android)
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Chainge
Primary Color: 
Secondary Color:

**Comment by pedrouid** [comment]
Already added it
