### ISSUE TITLE
Shinobi wallet

### ISSUE THREAD

**Issue by thanh-solashi** [WalletConnect/walletconnect-registry#284]
## App Logo (Required)
![xxhdpi](https://user-images.githubusercontent.com/49665448/133568051-6235f53f-7255-4e52-8416-d008a9c7a103.png)

## App Details (Required)
Type: Wallet
Name: Shinobi Wallet
Homepage Url: https://shinobi-wallet.net/
Chains supported: BTC, Ethereum, BSC, Matic

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/app/fgraph/id1572609905
Android Url: https://play.google.com/store/apps/details?id=io.fgraph.shinobiwallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 9f3cdb51420fac0f330e2db4d388e70e9d9981d3
