### ISSUE TITLE
Rabby Submission

### ISSUE THREAD

**Issue by vvvvvv1vvvvvv** [WalletConnect/walletconnect-registry#286]
## App Logo (Required)

![rabby](https://user-images.githubusercontent.com/86296331/133772416-3bfe0d8d-8688-492c-9f35-b75d32390fdb.png)

![rabby-large](https://user-images.githubusercontent.com/86296331/133773223-ad729bc9-d6c3-4262-ab0a-4594bea0556b.png)

## App Details (Required)
Type: Dapp (chrome extension wallet actually, lol)
Name: Rabby
Homepage Url: https://rabby.io/
Chains supported: ETH, BSC, xDai, Polygon, Fantom, OKEx, HECO, Arbitrum, Avalanche, Optimism, Celo (and more in future)

## App Url (Required - at least one)
Browser Url: https://chrome.google.com/webstore/detail/empty-title/acmacodkjbdgmoleebolmdjonilkdbch?hl=zh-CN

Rabby is a chrome extension wallet, but we support WalletConnect when user use watch mode(i.e. work as a extension wallet as usual but sign via WalletConnect when signing, manage your private key in mobile wallet)

**Comment by pedrouid** [comment]
Added on commit e553831a6e18c4f30f34c7bc9f19d76cbfbb8426
