### ISSUE TITLE
Steakwallet submission

### ISSUE THREAD

**Issue by AlexBHarley** [WalletConnect/walletconnect-registry#292]
## App Logo (Required)

![steakwallet-256](https://user-images.githubusercontent.com/11168524/134498171-5ef5e78a-a4ca-433f-b1ce-e6f49bfd64f0.png)

## App Details (Required)
Type: *Wallet*
Name: Steakwallet
Homepage Url: https://steakwallet.fi
Chains supported: Ethereum, Celo, Fantom, Avalanche C Chain, Optimism, Arbitrum One, Binance, cosmoshub-4 with more coming soon.

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/steakwallet/id1569375204
Android Url: https://play.google.com/store/apps/details?id=fi.steakwallet.app
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: steakwallet://
Universal Link: https://steakwallet.fi

## Desktop Linking (Optional)
Deep Link: N/A
Universal Link: N/A

## Metadata (Optional)
Short Name: Steakwallet
Primary Color: #EF8784
Secondary Color: #8AFC6E

**Comment by pedrouid** [comment]
Added on commit e1b10cfc029160dbadf5b41ed38249b36fde06b8
