### ISSUE TITLE
GD Wallet App Submission

### ISSUE THREAD

**Issue by konglingllq** [WalletConnect/walletconnect-registry#296]
## App Logo (Required)
![logo](https://oss.seaio.cc/cee4d060-909d-4bce-b080-969c7003cf6a.png)

## App Details (Required)
Type: Wallet 
Name: GD Walleet
Homepage Url: https://open.seaio.cc/
Chains supported: BSC(56),

## App Url (Required - at least one)
Browser Url:
iOS Url: https://dapp-h5.seaio.cc/newsDetail/#/downLoad?lang=ZH
Android Url: https://dapp-h5.seaio.cc/newsDetail/#/downLoad?lang=ZH
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link: GDWalletWC:
Universal Link:

## Metadata (Optional)
Short Name:GDWallet
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 74e577ad701ce08060e7abf7910b41e329068ead
