### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by LoveBadBoy** [WalletConnect/walletconnect-registry#298]
## App Logo (Required)
![编组@2x的副本](https://user-images.githubusercontent.com/15629820/135402184-8c1819e9-a07c-4ee9-878c-0119cb542408.png)

## App Details (Required)
Type: Wallet
Name:Binana
Homepage Url:http://www.binana.top/
Chains supported: Ethereum,TRX

## App Url (Required - at least one)
Browser Url:
iOS Url:https://testflight.apple.com/join/KH0E6Tbk
Android Url:http://www.binana.top/#/home
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:https://master.tokenone.app

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Binana
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 37d034e613054a92ae087d538889ce4c89e60265
