### ISSUE TITLE
add hashkey me to regitry

### ISSUE THREAD

**Issue by MrWude** [WalletConnect/walletconnect-registry#3]
## App Logo (Required)
(Attach image here)
![hashkeyme](https://user-images.githubusercontent.com/5791629/111405669-d998ec80-870b-11eb-9bfa-ad13d9d2c219.png)

## App Details (Required)
Type: Wallet
Name:HashKey Me
Homepage Url:https://me.hashkey.com/
Chains supported:["eip155:1"]

## App Url (Required - at least one)
Browser Url:
iOS Url:https://apps.apple.com/us/app/hashkey-me/id1547228803
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: hashme
Universal Link:https://me.hashkey.com

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:HashKey Me
Primary Color:rgb(254, 142, 63)
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit d1558b8e5d024d5599b81939d457561a91eabe66

**Comment by MrWude** [comment]
there was an error 

I filled in the template moblile linking

Mobile Linking (Optional)
Deep Link: hashme
Universal Link:https://me.hashkey.com

Desktop Linking (Optional)
Deep Link:
Universal Link:


but commit code as follow

"mobile": {
      "native": "",
      "universal": ""
    },
    "desktop": {
      "native": "hashme:",
      "universal": "https://me.hashkey.com"
    },

thank you for update
