### ISSUE TITLE
New App Submission - ICRE8

### ISSUE THREAD

**Issue by ragsonweb** [WalletConnect/walletconnect-registry#302]
## App Logo (Required)
![icre8-logo](https://user-images.githubusercontent.com/3082519/135729588-0eb56f3f-9f4b-477b-831a-c47c4161d3bc.png)
## App Details (Required)
Type: Dapp
Name: ICRE8
Homepage Url: https://icreatecrypto.com/
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://icreatecrypto.com/

**Comment by pedrouid** [comment]
I couldnt find any example that it supported Walletconnect
