### ISSUE TITLE
AirGap Wallet

### ISSUE THREAD

**Issue by AndreasGassmann** [WalletConnect/walletconnect-registry#305]
## App Logo (Required)
![airgap-wallet-logo](https://user-images.githubusercontent.com/680814/135846462-10e9c1f3-b695-4a94-a7bb-7d344f995ba8.png)

## App Details (Required)
Type: Wallet
Name: AirGap
Homepage Url: https://www.airgap.it
Chains supported: Ethereum, Bitcoin, Tezos, Shielded Tezos, æternity, Cosmos, Polkadot, Kusama, Groestlcoin, Moonriver.

## App Url (Required - at least one)
Browser Url: https://wallet.airgap.it
iOS Url: https://itunes.apple.com/us/app/airgap-wallet/id1420996542?l=de&ls=1&mt=8
Android Url: https://play.google.com/store/apps/details?id=it.airgap.wallet
Mac Url: https://github.com/airgap-it/airgap-wallet/releases
Windows Url: https://github.com/airgap-it/airgap-wallet/releases
Linux Url: https://github.com/airgap-it/airgap-wallet/releases

## Mobile Linking (Optional)
Deep Link: airgap-wallet://
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: AirGap
Primary Color: RGB(80, 36, 159)
Secondary Color: RGB(0, 232, 208)

**Comment by pedrouid** [comment]
Added on commit 6d76af8f59c8b7f8fb7dca879ba99eba35fd1e88
