### ISSUE TITLE
Fuse staking Dapp Submission

### ISSUE THREAD

**Issue by LiorAgnin** [WalletConnect/walletconnect-registry#307]
## App Logo (Required)
(Attach image here)
![android-chrome-512x512](https://user-images.githubusercontent.com/30021476/135991042-de0f89fe-6148-4b86-9b73-ebc09f8087de.png)

## App Details (Required)
Type: Dapp
Name: Fuse staking Dapp
Homepage Url: https://fuse.io/
Chains supported: Fuse Network

## App Url (Required - at least one)
Browser Url: https://staking.fuse.io/

## Mobile Linking (Optional)
Deep Link: 
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color: #031928
Secondary Color: #f8ff00

**Comment by pedrouid** [comment]
Added on commit 3c74f704a38e2fcb4a0e96193e15639702ca8015
