### ISSUE TITLE
uvtoken wallet App Submission

### ISSUE THREAD

**Issue by lianghuipinglz** [WalletConnect/walletconnect-registry#318]
## App Logo (Required)
![logo](https://m.uvtoken.com/img/img.png)

## App Details (Required)
Type: Wallet
Name: Uvtoken
Homepage Url: https://www.uvtoken.com
Chains supported: ETH,BTC,BNB,OKT,TRX,HT,TAFT

## App Url (Required - at least one)
Browser Url:https://www.uvtoken.com/
iOS Url:https://apps.apple.com/us/app/uvtoken/id1552556395
Android Url:https://wallet.uvtoken.com/static/download/android/uvtoken.apk
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: 
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Im sorry but your website doesnt work... your app store has one review without comments and this just doesnt seem to be legit

**Comment by yuyangjack** [comment]
> Im sorry but your website doesnt work... your app store has one review without comments and this just doesnt seem to be legit
Hi, can you see what your exit IP is? Let's find out the reason why it can't be opened, and then Ping www.uvtoken.com. Let's look at the resolved address
