### ISSUE TITLE
Tyrell-Yutani - New App Submission

### ISSUE THREAD

**Issue by DrJonesCGEye** [WalletConnect/walletconnect-registry#319]
## App Logo (Required)
![logo512](https://user-images.githubusercontent.com/25898147/137088280-d2dfa906-d501-4509-9faa-256a8fcdeade.png)

## App Details (Required)
Type: Dapp
Name: Tyrell-Yutani HUB
Homepage Url: https://tyrell-yutani.app
Chains supported: 1, 4 ( ETH main & rinkeby )

## App Url (Required - at least one)
Browser Url: https://tyrell-yutani.app/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: TY_Hub
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 957badef093e0031cbc2fddfcb307b1d39b1406c
