### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by ProninPS** [WalletConnect/walletconnect-registry#320]
## App Logo (Required)
![applogo_460afcc7ac](https://user-images.githubusercontent.com/15210716/137185765-bbd44ca6-3260-444f-8ba4-2fc5fbf2cfc6.png)

## App Details (Required)
Type: Dapp
Name: ChangeNow
Homepage Url: https://changenow.io
Chains supported: ETH

## App Url (Required - at least one)
Browser Url: 
iOS Url: https://apps.apple.com/us/app/id1518003605
Android Url: https://play.google.com/store/apps/details?id=io.changenow.changenow
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: changenow://
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: ChangeNow
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit c9187cf75bdc2f82df52786680c1fccab2a1e58f
