### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by windswrold** [WalletConnect/walletconnect-registry#322]
## App Logo (Required)
(Attach image here)
![icon](https://user-images.githubusercontent.com/13443539/137281179-2ccfa007-be1f-494e-9812-d4f834713bfd.png)

## App Details (Required)
Type: Wallet
Name:PayTube
Homepage Url:https://www.paytube.io/
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url:
iOS Url:https://apps.apple.com/us/app/paytube/id1574456998
Android Url:https://play.google.com/store/apps/details?id=com.paytube.wallet.zkwallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:PayTube
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 809468cab00bdb5bd7200c326d3294ddbeac9db3
