### ISSUE TITLE
New App Submission: SecuX Hardware Wallet

### ISSUE THREAD

**Issue by woody0529** [WalletConnect/walletconnect-registry#324]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/48586331/137440782-964f5e32-100f-4524-a747-4281b5c6cfb0.png)

## App Details (Required)
Type: Wallet
Name: SecuX
Homepage Url: https://secuxtech.com/
Chains supported: BTC, ETH, BSC, TRON, DGB, XLM, ADA, XRP, DOGE

## App Url (Required - at least one)
Browser Url: https://wallet.secuxtech.com/secuxess/#/
iOS Url: https://apps.apple.com/tw/app/secux-mobile/id1477437607
Android Url: https://play.google.com/store/apps/details?id=com.secux.mobile&hl=zh_TW&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: SecuX
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit f435522575fec7e961fed1190f7b2c965fe056b2
