### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by ziyue530** [WalletConnect/walletconnect-registry#328]
## App Logo (Required)

![eyesfi](https://user-images.githubusercontent.com/15965129/137895878-516d88a1-059c-47f8-97bf-c4077c12f9c7.png)

## App Details (Required)
Type: Dapp
Name: eyesfi
Homepage Url:https://www.eyesfi.com/
Chains supported:

## App Url (Required - at least one)
Browser Url:https://www.eyesfi.com/
iOS Url:https://www.eyesfi.com/
Android Url:
Mac Url:https://www.eyesfi.com/
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 5829cf3ae443065fbfa2ee3138b2cf41080d8dc9
