### ISSUE TITLE
BlockBank

### ISSUE THREAD

**Issue by rakovvlad** [WalletConnect/walletconnect-registry#329]
## App Logo (Required)
![apple-touch-icon-2](https://user-images.githubusercontent.com/16413557/137896091-1869efd3-f6b6-4098-8c5e-6e17fedfa89d.png)

## App Details (Required)
Type: Wallet
Name: BlockBank
Homepage Url: blockbank.ai
Chains supported: etc, bsc, btc

## App Url (Required - at least one)
iOS Url: https://apps.apple.com/us/app/blockbank/id1460965460
Android Url: https://play.google.com/store/apps/details?id=com.aibb.wallet

## Metadata (Optional)
Short Name: BBANK
Primary Color: f26422
Secondary Color: fff

**Comment by pedrouid** [comment]
Added on commit f1c29a7c02b2f7990c4f52bf7fd285013d890b95
