### ISSUE TITLE
New App Submission: Swapzone

### ISSUE THREAD

**Issue by trapofmirrors** [WalletConnect/walletconnect-registry#33]
## App Logo (Required)
![In47y 9t1_400x400](https://user-images.githubusercontent.com/82805768/115211892-ae3d5f00-a108-11eb-86af-ae3543f104dd.png)

## App Details (Required)
Type: Dapp
Name: Swapzone
Homepage Url: https://swapzone.io/
Chains supported: Bitcoin, Ethereum, Binance Chain, TRON, OMNI, ONT, NEO, etc. 

## App Url (Required - at least one)
Browser Url: https://swapzone.io/
iOS Url: 
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Swapzone
Primary Colors: F10286 + 25B7EB
Secondary Color:

**Comment by trapofmirrors** [comment]
Adding screenshots of our exchange page just in case to demonstrate how it looks:

![photo_2021-04-06_19-06-43](https://user-images.githubusercontent.com/82805768/115674639-880cfe80-a356-11eb-9027-b7cadd141469.jpg)
![photo_2021-04-06_19-06-45](https://user-images.githubusercontent.com/82805768/115674640-88a59500-a356-11eb-90aa-b4201790fefd.jpg)

**Comment by pedrouid** [comment]
Added on commit https://github.com/WalletConnect/walletconnect-registry/commit/e61b7f034a5175e03ef019d1d0d16697e785cb4f
