### ISSUE TITLE
Raven Protocol

### ISSUE THREAD

**Issue by sherm8n** [WalletConnect/walletconnect-registry#331]
## App Logo (Required)
![image](https://user-images.githubusercontent.com/1237709/138009758-6c2ae80c-225c-48e8-8a3e-ca826018a14f.png)

## App Details (Required)
Type: Dapp
Name: Raven Protocol Staking
Homepage Url: https://steak.ravenprotocol.com/
Chains supported: BEP2 (Binance Chain)

## App Url (Required - at least one)
Browser Url: https://steak.ravenprotocol.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 80d3098932ca13b3cc3da8b83c413bd15b5b9727
