### ISSUE TITLE
ViaWallet

### ISSUE THREAD

**Issue by wDemonX** [WalletConnect/walletconnect-registry#332]
## App Logo (Required)

![icon-1024](https://user-images.githubusercontent.com/21617727/138241141-408d26b5-9ed8-4fb9-9462-264da7e19caf.png)

## App Details (Required)
Type: Wallet
Name: ViaWallet
Homepage Url: https://viawallet.com/
Chains supported: Bitcoin, BitcoinCash, BitcoinSV, Litecoin, Dogecoin, Cosmos, Ethereum, EthereumClassic, SimpleLedger, Dash, Tron, Freecash, Xrp, Stellar, Decred, Tezos, Zcash, Kava, Irisnet, DigiByte, Lbrycredits, Kusama, Polkadot, Zilliqa, Algorand, Ravencoin, Ontology, VeChain, Icon, SmartChain, NervosCKB, ConfluxNetwork, Horizen, Handshake, HuobiECOChain, Near, CoinExSmartChain, Syscoin, Polygon, Ecash, Ergo, Cardano.

## App Url (Required - at least one)
Browser Url: https://explorer.viawallet.com/
iOS Url: https://apps.apple.com/us/app/viawallet/id1462031389
Android Url: https://play.google.com/store/apps/details?id=com.viabtc.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link: https://viawallet.com/.well-known/

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Already added to the registry

**Comment by wDemonX** [comment]
> Already added to the registry

Why I can not find my Wallet in the WalletConnect list when I prepare to connect to ?
