### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by kelcheone** [WalletConnect/walletconnect-registry#334]
## App Logo (Required)
https://assets.website-files.com/6074773e5354390d19151475/60c86af9254af11894ff971b_export.png

## App Details (Required)
Type:  Dapp
Name: Perpetual protocol
Homepage Url: https://perp.fi
Chains supported: Xdai, Arbitrum

## App Url (Required - at least one)
Browser Url: https://perp.exchange
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Perp
Primary Color: #3ceaaa
Secondary Color:  #03bce4

**Comment by pedrouid** [comment]
This looks great but I can't see the WalletConnect integration 😢
