### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by veerChauhan** [WalletConnect/walletconnect-registry#335]
## App Logo (Required)
![swift](https://user-images.githubusercontent.com/26132769/138535235-e1217696-415c-4a11-ba6c-952a30e29979.png)

## App Details (Required)
Type: Wallet or Dapp
Name: Wethio Wallet
Homepage Url:
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=com.wethiowallet&hl=en_IN&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Could fill the form a little more? Im not really sure where WalletConnect is being used
