### ISSUE TITLE
New App Submission: Mushrooms Finance

### ISSUE THREAD

**Issue by mushroomsforest** [WalletConnect/walletconnect-registry#336]
## App Logo (Required)
![image](https://raw.githubusercontent.com/mushroomsforest/deployment/main/logos/mushrooms256.png)

## App Details (Required)
Type: Dapp
Name: Mushrooms Finance
Homepage Url: https://www.mushrooms.finance/
Chains supported: Ethereum, Binance Smart Chain, Polygon, Fantom

## App Url (Required - at least one)
Browser Url: https://www.mushrooms.finance/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: MM
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Already in the registry
