### ISSUE TITLE
New App Submission - Orange Wallet

### ISSUE THREAD

**Issue by thelazyindian** [WalletConnect/walletconnect-registry#338]
## App Logo (Required)
![App_Icon](https://user-images.githubusercontent.com/24515192/138693142-4564ead8-697a-41df-9e01-dcb69b54a774.png)

## App Details (Required)
Type: Wallet
Name: Orange Wallet
Homepage Url: https://orangewallet.app/
Chains supported: Matic

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=org.orange.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: orangewallet:
Universal Link: https://link.orangewallet.app

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Orange
Primary Color: #EB5B56
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 3d0d945c7b8251e8c76f6a5ba0534a8337460b4e
