### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by nhnpro** [WalletConnect/walletconnect-registry#341]
## App Logo (Required)
![logo](https://user-images.githubusercontent.com/18005805/139083103-0d07c000-17e9-4353-a4ac-1f7994041ebe.png)

## App Details (Required)
Type: Dapp
Name: My Defi Pet
Homepage Url: https://mydefipet.com/
Chains supported: BSC, KARDIA

## App Url (Required - at least one)
Browser Url: https://play.mydefipet.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:mydefipet
Universal Link:mydefipet

## Desktop Linking (Optional)
Deep Link:mydefipet
Universal Link:mydefipet

## Metadata (Optional)
Short Name: DPet
Primary Color: #FFCB0F
Secondary Color:

**Comment by pedrouid** [comment]
I tried connecting with WalletConnect but couldnt find the option
