### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by NeftiWallet** [WalletConnect/walletconnect-registry#342]
## App Logo (Required)

![neftipedia 200x200](https://user-images.githubusercontent.com/93321247/139240647-4726cd52-bfde-4728-9019-4a495231d60c.png)

## App Details (Required)
Type: Wallet 
Name: NEFTiPEDiA
Homepage Url: https://neftipedia.com/
Chains supported: Binance Smart Chain

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=com.NEFTiPEDiA.mp
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on 8b27c2eb12318b77e24431eaebaeb5dfffe844b2
