### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by ludowkm** [WalletConnect/walletconnect-registry#346]
## App Logo (Required)
![Avacus](https://user-images.githubusercontent.com/52436608/139631790-175c5b0e-ca69-4b87-a450-73389dc648c2.png)
## App Details (Required)
Type: Wallet
Name: Avacus
Homepage Url: https://avacus.cc
Chains supported: ETH

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/id1339638445
Android Url: https://play.google.com/store/apps/details?id=com.floortracks.avacus
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: avacus://
Universal Link: https://avacus.app.link

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit c9c05753f7668c856afbf5d39601181d6a8d879a
