### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by AndreyMaksimkin** [WalletConnect/walletconnect-registry#347]
## App Logo (Required)

![icon-linen](https://user-images.githubusercontent.com/6286808/139573876-2b59f7bf-eb58-4ef2-a30a-f436966b11a0.png)

## App Details (Required)
Type: Wallet
Name: Linen
Homepage Url: https://linen.app/
Chains supported: ETH(1), Kovan(42), Matic(137), Mumbai(80001)

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/app/linen-app-investing-in-defi/id1480509067
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link: https://linen.app/

## Desktop Linking (Optional)
Deep Link:
Universal Link: 

## Metadata (Optional)
Short Name: "Linen"
Primary Color: #019FBA
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit b3d54fcf5bfddf61c9a6dbd4e2baba11e146811b

**Comment by AndreyMaksimkin** [comment]
@pedrouid Sorry for the mistake. Is it possible to change Universal Link for mobile linking from https://linen.app to https://linen.page.link
