### ISSUE TITLE
New App Submission: Alkemi Network

### ISSUE THREAD

**Issue by brandoncurtis** [WalletConnect/walletconnect-registry#348]
closed by #304 

## App Logo (Required)
(Attach image here)

## App Details (Required)
Type: Dapp
Name: Alkemi Network
Homepage Url: https://alkemi.network/
Chains supported: Ethereum (EIP155:1)

## App Url (Required - at least one)
Browser Url: https://earn.alkemi.network/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Alkemi
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on PR #304
