### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by uselessjhtest** [WalletConnect/walletconnect-registry#349]
## App Logo (Required)
https://app.uselesscrypto.com/swap/static/media/swapper_logo.4840bddf.png

## App Details (Required)
Type: Dapp
Name: U-Swap
Homepage Url: https://app.uselesscrypto.com/swap/
Chains supported: bep-20

## App Url (Required - at least one)
Browser Url: https://app.uselesscrypto.com/swap/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 2c0c2eb8b62469253873f62dce4aa9101ea89522
