### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by PandaX233** [WalletConnect/walletconnect-registry#35]
## App Logo (Required)
![“app-icon-iTunesArtwork”的副本](https://user-images.githubusercontent.com/80445698/115349551-920fef80-a1e6-11eb-98fa-d67a3246fb1c.png)

## App Details (Required)
Type: Wallet
Name: f(x)Wallet
Homepage Url: https://download.functionx.io/
Chains supported: Bitcoin, Ethereum, Function X and more in future

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/us/app/f-x-wallet-by-pundi-x-labs/id1504798360
Android Url: https://play.google.com/store/apps/details?id=com.pundix.functionx
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 105557a3d982aa622b638965798dd6c1acf41fdb
