### ISSUE TITLE
New App Submission: CeloTerminal

### ISSUE THREAD

**Issue by zviadm** [WalletConnect/walletconnect-registry#350]
## App Logo (Required)

(Attach image here)

![icon](https://user-images.githubusercontent.com/517937/139967319-a04df21c-43c4-4a83-952c-233aba5b72a7.png)

## App Details (Required)

Type: Wallet
Name: CeloTerminal
Description: The one-stop shop for everything Celo
Homepage Url: https://celoterminal.com
Chains supported: eip155:42220
Versions supported: v1

## App Url (Required - at least one)

Browser Url: https://celoterminal.com
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: CeloTerminal
Primary Color: 
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit cad53938076f256eb9054e30d5918a7d89bac780

**Comment by zviadm** [comment]
Hey @pedrouid , CeloTerminal is a Wallet, but it seems that you added it in dapps.json file by mistake.
