### ISSUE TITLE
New App Submission - Krystal Wallet

### ISSUE THREAD

**Issue by toidv** [WalletConnect/walletconnect-registry#353]
## App Logo (Required)

![Krystal_Logo](https://user-images.githubusercontent.com/11902642/140305310-a42d98f4-7390-44a1-9edc-55943b6ad14d.png)

## App Details (Required)

Type: Wallet
Name: Krystal 
Description: Krystal is a secure and simple way to access the best DeFi services on a single platform
Homepage Url: https://krystal.app/
Chains supported: Ethereum, Binance Smart Chain, Polygon (Matic), Avalanche
Versions supported:

## App Url (Required - at least one)

Browser Url: https://krystal.app/
iOS Url: https://apps.apple.com/vn/app/krystal-one-platform-all-defi/id1558105691
Android Url: https://play.google.com/store/apps/details?id=com.kyrd.krystal
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: krystalWallet:
Universal Link:

## Desktop Linking (Optional)

Deep Link: 
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit 7bbe312bc9f997bb58be43b23bb0e0b5cd0c14aa
