### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by sayjeyhi** [WalletConnect/walletconnect-registry#356]
## App Logo (Required)
![ezgif com-gif-maker-removebg-preview](https://user-images.githubusercontent.com/6254009/140606138-ef4f2357-7360-435f-9b01-75feec22b245.png)

## App Details (Required)

Type: Dapp
Name: Yooshi
Description:
Homepage Url: https://yooshi.io/
Chains supported: bsc
Versions supported:

## App Url (Required - at least one)

Browser Url: https://yooshi.io/
iOS Url: https://yooshi.io/
Android Url: https://yooshi.io/
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
