### ISSUE TITLE
New App Submission - NeftiWallet

### ISSUE THREAD

**Issue by NEFTiPEDiA** [WalletConnect/walletconnect-registry#359]
## App Logo (Required)
https://neftipedia.com/assets/img/nefti-256x256.png
(Attach image here)
![nefti-256x256](https://user-images.githubusercontent.com/93321247/140700120-ae592f04-5483-4197-81cf-5162637e1471.png)

## App Details (Required)
The platform's NFT WALLET allows storing of the NFTs securely on the blockchain.

Type: Wallet 
Name: NeftiWallet
Description: The platform's NFT WALLET allows storing of the NFTs securely on the blockchain.
Homepage Url: https://neftipedia.com/
Chains supported: binance smart chain
Versions supported: 

## App Url (Required - at least one)

Browser Url: 
iOS Url: 
Android Url: https://play.google.com/store/apps/dev?id=5876892422790110815
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: nefti://nefti.id/asset/
Universal Link: https://nefti.id/asset/

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: NFT
Primary Color: #37747E
Secondary Color: #58595B

**Comment by chadyj** [comment]
Added to the cloud registry.
