### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by parminder-gill** [WalletConnect/walletconnect-registry#360]
## App Logo (Required)
![ancrypto_logo](https://user-images.githubusercontent.com/83643012/140740485-8ae6dc8f-3b4c-4709-9ec5-fffa714e410c.png)

## App Details (Required)

Type: Wallet
Name: Ancrypto Wallet
Description:
Homepage Url: https://www.antiersolutions.com/
Chains supported: Ethereum, Binance Smart Chain, Tron, Bitcoin, Bitcoin Cash, LiteCoin, DogeCoin, Polkadot, Kosama, Tezos
Versions supported:

## App Url (Required - at least one)

Browser Url: https://www.antiersolutions.com/
iOS Url: https://apps.apple.com/in/app/ancrypto-wallet/id1453657650
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: ancrypto://app
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
