### ISSUE TITLE
New App Submission (Balancer)

### ISSUE THREAD

**Issue by TomAFrench** [WalletConnect/walletconnect-registry#361]
## App Logo (Required)
https://raw.githubusercontent.com/balancer-labs/pebbles/master/images/pebbles-pad.svg

https://github.com/balancer-labs/pebbles contains all variants of logo in case you need a version with a background etc.
## App Details (Required)

Type: Dapp
Name: Balancer
Description: Automated portfolio manager and trading platform
Homepage Url: https://balancer.fi
Chains supported: Ethereum, Arbitrum, Polygon
Versions supported: 1 (assuming this means WC versions)

## App Url (Required - at least one)

Browser Url: https://app.balancer.fi
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Balancer
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
