### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by AlpineDex** [WalletConnect/walletconnect-registry#362]
## App Logo (Required)

https://docs.alpinedex.finance/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FduzAi1VXvVmkteyEf2zC%2Fuploads%2FToJALAd42bRGxzDre2KN%2Flogo%204.png?alt=media&token=3880a9dd-4ce2-4f89-80df-ee2539405c75

## App Details (Required)

Type:  Dapp
Name: Alpine DEX
Description: Alpine Dex is a decentralized cryptocurrency exchange where you can 
Buy, trade, farm, stake, and earn crypto at the lowest rates.
 
Homepage Url: https://alpinedex.finance
Chains supported: BSC 
Versions supported: All

## App Url (Required - at least one)

Browser Url: https://alpinedex.finance
iOS Url: https://alpinedex.finance
Android Url: https://alpinedex.finance
Mac Url: https://alpinedex.finance
Windows Url: https://alpinedex.finance
Linux Url: https://alpinedex.finance

## Mobile Linking (Optional)

Deep Link: https://alpinedex.finance
Universal Link: https://alpinedex.finance

## Desktop Linking (Optional)

Deep Link: https://alpinedex.finance
Universal Link: https://alpinedex.finance

## Metadata (Optional)

Short Name: Alpine DEX
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
https://alpinedex.finance couldn't be accessed. There is a password protection.
Please resubmit to the cloud registry when this is resolved.
