### ISSUE TITLE
New App Submission - S-ONE Wallet

### ISSUE THREAD

**Issue by s-one-system** [WalletConnect/walletconnect-registry#369]
## App Logo (Required)

![sone](https://user-images.githubusercontent.com/79563509/141281654-cccb1658-5dab-4fe9-8299-3b2a31067361.png)

## App Details (Required)

Type: Wallet
Name: S-ONE Wallet
Description: S-ONE Wallet is a convenient and secure multicoin P2P wallet for S-ONE Finance users. S-ONE Wallet is the official wallet of S-ONE Finance. SONE holders can easily store, transfer, exchange, and manage crypto assets with just one wallet.
Homepage Url: https://s-one.finance/
Chains supported: ETH, BSC, BTC

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/s-one-wallet/id1564871193
Android Url: https://play.google.com/store/apps/details?id=sone.finance.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: sone://
Universal Link: https://sonewallet.app

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by s-one-system** [comment]
@pedrouid please check this issue. we need display app on walletconnect.

**Comment by chadyj** [comment]
This has now been added to the cloud registry
