### ISSUE TITLE
New App Submission - MoonCat World

### ISSUE THREAD

**Issue by stephenmsullivan** [WalletConnect/walletconnect-registry#37]
## App Logo (Required)
![icon-1024](https://user-images.githubusercontent.com/1365408/125201793-602a8a00-e225-11eb-9486-928adb20976c.png)

## App Details (Required)
Type: Dapp
Name: MoonCat World
Homepage Url: https://mooncatworld.com
Chains supported:

## App Url (Required - at least one)
Browser Url:
iOS Url:  https://apps.apple.com/us/app/mooncat-world/id1565672505
Android Url: https://play.google.com/store/apps/details?id=com.jackpottechnologies.mooncatworld
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
both iso and android app urls are broken

**Comment by stephenmsullivan** [comment]
Hi,  I can't get the android or ios URL live until the app works.  They need to be reviewed with it working.  

For the ico file.  This is the wordpress generated one.  Do you need something else?
https://mooncatworld.com/wp-content/uploads/2021/04/cropped-icon-1024-192x192.png\

Thanks

**Comment by stephenmsullivan** [comment]
Hi,  We've shipped an update of the app on iOS and Android but it still has the wrong app for the wallet connect.  can we get this submission approved.

**Comment by pedrouid** [comment]
Added on commit 39a034b
