### ISSUE TITLE
Add Deep & Universal Link for SecuX hardware Wallet

### ISSUE THREAD

**Issue by woody0529** [WalletConnect/walletconnect-registry#370]
## App Logo (Required)

(Attach image here)

## App Details (Required)

Type: Wallet or Dapp
Name:
Description:
Homepage Url:
Chains supported:
Versions supported:

## App Url (Required - at least one)

Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: secux://
Universal Link: https://wallet.secuxtech.com

## Desktop Linking (Optional)

Deep Link: secux://
Universal Link: https://wallet.secuxtech.com

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
You can now manage this listing yourself for any new updates. See this blog post https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33
