### ISSUE TITLE
New App Submission - Useless Dapp

### ISSUE THREAD

**Issue by uselessjhtest** [WalletConnect/walletconnect-registry#373]
## App Logo (Required)

[https://app.uselesscrypto.com/swap/static/media/swapper_logo.4840bddf.png](https://app.uselesscrypto.com/swap/static/media/swapper_logo.4840bddf.png)

## App Details (Required)

Type: Dapp
Name: U-Swap
Description:
Homepage Url: https://app.uselesscrypto.com/
Chains supported:
Versions supported:

## App Url (Required - at least one)

Browser Url: https://app.uselesscrypto.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Closing. Incomplete submission.
Please re-submit to the cloud registry.
