### ISSUE TITLE
Uvtoken

### ISSUE THREAD

**Issue by yaoyf888** [WalletConnect/walletconnect-registry#374]
## App Logo (Required)
![logo](https://m.uvtoken.com/img/img.png)
(Attach image here)

## App Details (Required)

Type: Wallet 
Name:Uvtoken
Description:
Homepage Url:https://www.uvtoken.com
Chains supported: btc,eth,erc20,trx,trc20,bsc,heco,okex,dot,ksm
Versions supported:

## App Url (Required - at least one)

Browser Url:https://www.uvtoken.com/
iOS Url:https://apps.apple.com/hk/app/uvtoken/id1552556395
Android Url:https://wallet.uvtoken.com/static/download/android/uvtoken.apk
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:UvToken://

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by yaoyf888** [comment]
@pedrouid We hope to register in the WalletConnect registry, please help to approve it.
Our official website is only a website to display wallet functions and download. If you need to experience our functions, you can complete it through our ios app or Android app. We really hope that you can approve it.

**Comment by yuyangjack** [comment]
There are thousands of users use uvtoken every day in the world. A large number of fans want to improve the user experience. Please help us approve it in order to deeply support walletconnect. @pedrouid

**Comment by chadyj** [comment]
Added to the cloud registry.
