### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by Joelixy** [WalletConnect/walletconnect-registry#375]
## App Logo (Required)

![ios-marketing](https://user-images.githubusercontent.com/18097224/141735144-a02e48f2-392e-494a-9fed-ce6b37a15a5c.png)

## App Details (Required)

Type: Dapp
Name: BitWell
Description:
Homepage Url: https://bitwellex.com/
Chains supported:
Versions supported:

## App Url (Required - at least one)

Browser Url: http://bitwellex.com/
iOS Url: https://apps.apple.com/gb/app/bitwell/id1515072664
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link: www.bitwellex.com

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
I tried to test the WalletConnect integration, but I couldn't find out how to connect with WalletConnect.
Closing for now, but please feel free to resubmit to the new cloud registry https://walletconnect.com
