### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by sebarmled** [WalletConnect/walletconnect-registry#376]
## App Logo (Required)
![Cryptnox Logo_only_white_on_deep blue](https://user-images.githubusercontent.com/38683630/141854334-791eef5d-d15d-44eb-995d-fde4e2cc23c1.png)

## App Details (Required)

Type: Wallet
Name: CryptnoxApp
Description: IOS app to use our smartcards as hardware wallet via NFC
Homepage Url: www.cryptnox.com
Chains supported: Ethereum Mainnet and most Layer 2 (Polygon..etc..) via WalletConnect
Versions supported: WalletConnect 1.0

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/app/id1583011693
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
