### ISSUE TITLE
New App Submission - Spot Wallet

### ISSUE THREAD

**Issue by lionel-alves** [WalletConnect/walletconnect-registry#377]
## App Logo (Required)

![icon_60pt@3x](https://user-images.githubusercontent.com/1184939/142038534-e2fbba17-fa44-475f-94d4-48851127647d.png)

## App Details (Required)

Type: Wallet
Name: Spot
Description: Spot is a mobile non-custodial wallet available on iOS and Android. It currently natively supports the following blockchains: Bitcoin, Ethereum, Solana, Tezos and more.

Homepage Url: https://www.spot-wallet.com
Chains supported: Ethereum Mainnet, Kovan & Rinkeby
Version supported: 1.0

## App Url (Required - at least one)

iOS Url: https://apps.apple.com/us/app/buy-bitcoin-spot-wallet-app/id1390560448
Android Url: https://play.google.com/store/apps/details?id=com.spot.spot

## Mobile Linking (Optional)

Deep Link: spot://
Universal Link: https://spot.so/

## Metadata (Optional)

Short Name: Spot
Primary Color: #29C0FF
Secondary Color: #FC5789

**Comment by pedrouid** [comment]
Added on commit 3b66b33
