### ISSUE TITLE
New App Submission - MyWalliD

### ISSUE THREAD

**Issue by GuilhermeArsenio** [WalletConnect/walletconnect-registry#380]
## App Logo (Required)

![wallid-logo](https://user-images.githubusercontent.com/78441164/142224116-7fa859ea-6f43-4a40-a432-2987796a620b.png)

## App Details (Required)

Type: Wallet
Name: MyWalliD
Description: MyWalliD lets the user store and manage their own identities assets on the browser local memory and uses wallet keys to encrypt/decrypt ID assets data or to authenticate on the web3. 
Homepage Url: https://www.wallid.io/
Chains supported: Ethereum Mainnet & Rinkeby
Versions supported: 1.0

## App Url (Required - at least one)

Browser Url: https://chrome.google.com/webstore/detail/wallid-wallet/eknlkogikcabnjbjnhmjllabckeapdii

## Metadata (Optional)

Short Name: MyWalliD
Primary Color: #009FB1

**Comment by chadyj** [comment]
Added to the cloud registry.
