### ISSUE TITLE
New App Submission—CeloDance Wallet

### ISSUE THREAD

**Issue by bi23com** [WalletConnect/walletconnect-registry#383]
## App Logo (Required)
![logo](https://user-images.githubusercontent.com/6767618/142550808-3182d29d-e5fc-4fce-8936-5ee2b35e57b1.png)

## App Details (Required)

Type: Wallet
Name: CeloDance
Description: CeloDance is a Celo mobile wallet that supports the management of celo assets, you can transfer in or out of  CELO/cUSD/cEUR, and lock your CELO to staking. 
Homepage Url: http://celo.dance/
Chains supported:  Celo 
Versions supported:  version 2

## App Url (Required - at least one)

iOS Url: https://www.pgyer.com/JbDW
Android Url: https://www.pgyer.com/JbDW

## Mobile Linking (Optional)

Deep Link: celo://wallet/dappkit/celodance

**Comment by chadyj** [comment]
Added to the cloud registry.
