### ISSUE TITLE
New App Submission - mStable

### ISSUE THREAD

**Issue by dimsome** [WalletConnect/walletconnect-registry#392]
## App Logo (Required)

https://github.com/mstable/mStable-apps/blob/master/libs/icons/src/lib/circle/mta.svg

## App Details (Required)

Type: Dapp
Name: mStable
Description: Decentralised Stablecoin Ecosystem
Homepage Url: https://mstable.org/
Chains supported: Ethereum, Polygon
Versions supported: 1

## App Url (Required - at least one)

Browser Url: https://mstable.app
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: mStable
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Published on the cloud registry.
(finally! sorry about the delay :) )
