### ISSUE TITLE
App Info Update

### ISSUE THREAD

**Issue by dysquard** [WalletConnect/walletconnect-registry#397]
Hello, we'd like update some info of Go Pocket.

"mobile": {
"native": "gopocket:",
"universal": "https://gopocket.security/"
},
"desktop": {
"native": "",
"universal": ""
},
"metadata": {
"shortName": "Go Pocket",
"colors": {
"primary": "rgb(255, 255, 255)",
"secondary": ""
}

**Comment by chadyj** [comment]
You can now manage this listing yourself for any new updates. See this blog post https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33
