### ISSUE TITLE
New App Submission: Ambire Wallet

### ISSUE THREAD

**Issue by Ivshti** [WalletConnect/walletconnect-registry#398]
## App Logo
![ambire_favicon](https://user-images.githubusercontent.com/1247629/143858839-efda1e8e-d86c-46da-b740-d33cf465d8b3.png)

## App Details

Type: Wallet
Name: Ambire Wallet
Description: Ambire Wallet is a full featured non-custodial open-source wallet that focuses on DeFi and unifies the best earning opportunities, while solving common pain points of DeFi and Ethereum. It combines power, security and ease of use: you can pay gas in stablecoins, send batch transactions, there are no ERC20 approvals, and you can secure your account using Ledger/Trezor.
Homepage Url: https://www.ambire.com
Chains supported: Ethereum, Polygon, Avalanche, Binance Smart Chain
Versions supported: v1.x, v2.0 coming in a few weeks

## App Url
https://wallet.ambire.com - supports ?uri=... 

Browser Url: https://wallet.ambire.com 
iOS Url: N/A
Android Url: N/A
Mac Url: https://wallet.ambire.com 
Windows Url: https://wallet.ambire.com 
Linux Url: https://wallet.ambire.com 

## Desktop Linking

Deep Link: https://wallet.ambire.com 
Universal Link: https://wallet.ambire.com 

## Metadata

Short Name: Ambire
Primary Color: #aa6aff
Secondary Color: #80ffdb

**Comment by pedrouid** [comment]
Added on commit 7318e238ab218aaed3820c548d0f71de6d73847a
