### ISSUE TITLE
BRISE Wallet

### ISSUE THREAD

**Issue by bitrisetoken** [WalletConnect/walletconnect-registry#400]
## App Logo (Required)

![Untitled (512 x 512 px)](https://user-images.githubusercontent.com/87169757/144010937-e75e9e19-ad59-48f1-b176-81bc59d639c2.png)

## App Details (Required)

Type: Wallet or Dapp
Name: BRISE Wallet
Description: BRISE Wallet is the official crypto wallet of BRISE Token. You can send, receive and store coins and many other cryptocurrencies and digital assets safely and securely with the BRISE Wallet mobile app.
Homepage Url: www.bitgert.com
Chains supported: ERC20/BEP20
Versions supported: Android and iOS

## App Url (Required - at least one)

Browser Url: 
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=com.brise.wallet&hl=en_US&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
