### ISSUE TITLE
Metaspace App Submission

### ISSUE THREAD

**Issue by kajumito** [WalletConnect/walletconnect-registry#401]
## App Logo (Required)

![metaspace-logo](https://user-images.githubusercontent.com/15631080/144045941-b2a5af9a-5b09-41e6-8d1a-433158e07e64.png)

## App Details (Required)

Type: Dapp
Name: Metaspace 
Description: Metaspace is NFT -compatible web3 platform where users can own and access different type of virtual spaces - Experience, showcase and sell your NFTs
Homepage Url: https://metaspace.fi/
Chains supported: Ethereum
Versions supported: v1.x (web3-react)

## App Url (Required - at least one)

Browser Url: https://metaspace.fi/
iOS Url: https://metaspace.fi/
Android Url: https://metaspace.fi/
Mac Url: https://metaspace.fi/
Windows Url: https://metaspace.fi/
Linux Url: https://metaspace.fi/

## Metadata (Optional)

Short Name: Metaspace

**Comment by chadyj** [comment]
Added to the cloud registry.
