### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by coursewarefactory** [WalletConnect/walletconnect-registry#406]
## App Logo (Required)
![blockcerts-logo](https://user-images.githubusercontent.com/10476652/144637839-f6c422a1-40db-4f23-b54d-ab89c0a2b4e9.png)
(Attach image here)

## App Details (Required)

Type: Wallet or Dapp
Name: BCERTin wallet 
Description: The BCERTin wallet comes with a set of amazing tools to manage your business & life with unlimited cloud access.
Homepage Url: [blockcerts.com](blockcerts.com)
Chains supported: Ethereum
Versions supported: Mac, Windows, Linux

## App Url (Required - at least one)

Browser Url:
iOS Url: Comming soon
Android Url: [Version for Android](https://play.google.com/store/apps/details?id=com.blockcerts.BlockCerts&hl=en_US&gl=CA)
Mac Url: [Version for Mac OS](https://blockcerts.com/download-mac/?type=mac)
Windows Url: [Version for Windows](https://blockcerts.com/download-windows/?type=windows)
Linux Url: [Version for Debian](https://blockcerts.com/download-debian/?type=debian)

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: BCERTin wallet 
Primary Color: 76b53b
Secondary Color: 495849

**Comment by chadyj** [comment]
You can now manage this listing yourself for any new updates. See this blog post https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33
