### ISSUE TITLE
New App Submission (CoinUs Logo Change & New iOS Download Link)

### ISSUE THREAD

**Issue by coinus** [WalletConnect/walletconnect-registry#408]
## App Logo (Required)

![coinus_로고](https://user-images.githubusercontent.com/38288958/144777055-7ca4d1da-926d-4d0c-87bf-f5d6639d0047.png)

## App Details (Required)

Type: App Wallet
Name: CoinUs
Description: CoinUs is the first decentralized wallet in Korea to start safe management of virtual assets through transfer, swap, and wallet restore services.
Homepage Url: https://www.coinus.io/
Chains supported: BTC, ETH (ERC20), RVN (RVN Assets), Filecoin
Versions supported:

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/apple-store/id1584954032
Android Url: https://play.google.com/store/apps/details?id=com.theblockchain.coinus.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
You can now manage this listing yourself for any new updates.  See this blog post https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33
