### ISSUE TITLE
New App Submission: Layer

### ISSUE THREAD

**Issue by raxityo** [WalletConnect/walletconnect-registry#409]
## App Logo (Required)

![image](https://user-images.githubusercontent.com/767683/145259010-af7e2f2a-8432-4594-bea9-316c922b0e9c.png)

## App Details (Required)

Type: Wallet
Name: Layer
Description:
Homepage Url: https://layer.com
Chains supported: `eip155:1`
Versions supported: `1`

## App Url (Required - at least one)

Browser Url: https://layer.com
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: layer
Universal Link: https://layer.com

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: layer
Primary Color: `#000000`
Secondary Color: `#00FF6A`

**Comment by chadyj** [comment]
Closing, since this isn't publicly available.
Please resubmit to the cloud registry when launched.
