### ISSUE TITLE
New App Submission (Bull App)

### ISSUE THREAD

**Issue by wulangbnu** [WalletConnect/walletconnect-registry#41]
## App Logo (Required)
![BullApp_logo_512](https://user-images.githubusercontent.com/5148787/115808125-79891a80-a41c-11eb-9a2a-ab8a6ea3e953.png)

## App Details (Required)
Type: Wallet
Name: Bull App
Homepage Url: https://getbull.app/
Chains supported:   Ethereum (ETH), Binance Smart Chain(BSC), Conflux (CFX), Huobi ECO Chain(HECO) 

## App Url (Required - at least one)
Browser Url: 
iOS Url: https://apps.apple.com/app/id1558608737
Android Url: https://play.google.com/store/apps/details?id=crypto.wallet.chainapp
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit dc779e72007224448e3510585eadb93560683246
