### ISSUE TITLE
Fix Desktop Wallet Registry

### ISSUE THREAD

**Issue by Crytogenz** [WalletConnect/walletconnect-registry#410]
I have talked to Chad on Discord about some issues with some wallets on the wallet registry and was told to open a issue here 

I have been testing Walletconnect on a game dapp I am making and found that a lot of the desktop options dont actually work

1- Ledge Live only opens the app but does not prompt a connect option and when not got Leger Live installed it does nothing

2 - Tokenary is a browser extension wallet only on mac and looks like it does not even have wallet connect, also on clicking to connect it only links to their website which then links to the app store

3 - Infinity Wallet is the only wallet on the list that actually works, I click to connect and it opens in their app and connected or if not got the wallet it says I can download (Btw just as a notice I am actually using this wallet now over Metamask as it has way more features and better UX)

4 - Wallet 3 goes to a white page on clicking which is not great at all

5 - Ambire Wallet looks like a web wallet but it has no wallet connect option that I could find 

![image](https://user-images.githubusercontent.com/79938538/145222282-9625c6a4-b22a-4fdb-9de0-7c07f8ae1b1b.png)

I would like to recommend the wallet registry be cleaned up as I think UX is important and as a desktop user there is only really 2 options currently for desktop either I use Metamask browser extension or for Walletconnect I use Infinity Wallet as the rest of the options listed dont connect when clicking or dont have wallet connect option at all

**Comment by Ivshti** [comment]
5 - Ambire connects to WalletConnect-enabled dApps via the top right "dApps" menu (see attached). Once you have an account it automatically connects when you click the Ambire Wallet option in the desktop tab in your screenshot. You can also connect by clicking "Connect dApp" and paste in a WalletConnect URI
![Screenshot 2021-12-08 at 21-08-02 Ambire Wallet](https://user-images.githubusercontent.com/1247629/145268870-3a9dd072-500c-421f-9b87-5ee194e40aad.png)

**Comment by pedrouid** [comment]
Thanks @Crytogenz for your comment but I'm closing this issue since we discussed it shortly on Discord as well and I have a lot of submissions to triage
