### ISSUE TITLE
Frontier - New App Submission

### ISSUE THREAD

**Issue by vetri02** [WalletConnect/walletconnect-registry#412]
## App Logo (Required)

![Frontier](https://user-images.githubusercontent.com/313364/145544801-668b1d06-9a6f-4f1c-a88d-534087a8d619.png)

## App Details (Required)

Type: Wallet
Name: Frontier
Description: Your Front Seat to Crypto and DeFi
Homepage Url: https://www.frontier.xyz/
Chains supported: ethereum , binance smart chain, polygon, avalanche c-chain, tomochain

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/frontier-defi-wallet/id1482380988
Android Url: https://play.google.com/store/apps/details?id=com.frontierwallet&hl=en_IN&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: frontier://
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Frontier
Primary Color: #CC703C
Secondary Color: #FFFFFF

**Comment by pedrouid** [comment]
Added on commit 2020e10
