### ISSUE TITLE
CivTrade Submission

### ISSUE THREAD

**Issue by DexMan100** [WalletConnect/walletconnect-registry#413]
## App Logo (Required)

![CIV_logo500x500](https://user-images.githubusercontent.com/89242554/145601320-3c116f05-20bd-406d-b06c-43c4dd8598b6.jpg)

## App Details (Required)

Type: Dapp
Name: CivTrade
Description: Limit Trades for the Ethereum Mainnet
Homepage Url: https://civfund.org
Chains supported: id = 1 (Mainnet)
Versions supported: 1

## App Url (Required - at least one)

Browser Url: https://app.civfund.org
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
