### ISSUE TITLE
New App Submission - LZ Wallet

### ISSUE THREAD

**Issue by bachlongkocanh** [WalletConnect/walletconnect-registry#415]
## App Logo (Required)

![LZLogo](https://user-images.githubusercontent.com/28125294/146304192-42d1c284-4c5e-4ebd-9a94-e7eac20ffae5.png)

## App Details (Required)

Type: Wallet
Name: LZ Wallet
Description: LZ Wallet is the ideal wallet for storing and trading your digital assets securely and conveniently, specifically tailoured for the explosive growth of DeFi platforms and decentralized applications (DApps).
Homepage Url: https://lz.finance/home
Chains supported: Multi chain
Versions supported: 1

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/app/lz-wallet/id1581578160
Android Url: https://play.google.com/store/apps/details?id=com.launchzone.lzwallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
