### ISSUE TITLE
New App Submission- Lead Wallet

### ISSUE THREAD

**Issue by humaidhusain98** [WalletConnect/walletconnect-registry#417]
## App Logo (Required)

(Attach image here)
![LEAD WALLET](https://user-images.githubusercontent.com/66073877/146558851-2fb7b12a-b0b6-4a36-8ce5-492cbfdeab70.jpg)

## App Details (Required)

Type: Wallet
Name: Lead Wallet
Description:   Lead Wallet is a multi-blockchain and multi-functional decentralized crypto wallet application with web3 DApp browser feature, NFT and custom fungible token wallet support, fiat-to-crypto swap support, Dex Aggregator feature,  Multisender support, NFT and utility marketplace feature.
Homepage Url: [leadwallet.io](https://leadwallet.io)
Chains supported: BTC, ETH, BSC, Tron, Polygon, RSK, Conflux, Polkadot, Kusama, Celo, Dogecoin, Dash. (more chains in the pipeline)
Versions supported: Mobile and wallet connect

## App Url (Required - at least one)

Browser Url: https://leadwallet.io/wallet
iOS Url: https://apps.apple.com/tt/app/lead-wallet/id1578704913
Android Url: https://play.google.com/store/apps/details?id=com.leadWallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:  leadwallet://wallet-connect/
Universal Link:  https://ws.leadwallet.io/api/api/v1/wallet-connect/

## Desktop Linking (Optional)

Deep Link:  leadwallet://wallet-connect/
Universal Link: https://ws.leadwallet.io/api/api/v1/wallet-connect/

## Metadata (Optional)

Short Name: Lead
Primary Color:  Pink (F90A88)
Secondary Color: Blue (3E2779)

**Comment by Hendobox** [comment]
Hi, could you please follow up on this request? Thank you

**Comment by chadyj** [comment]
Added to the cloud registry.

**Comment by Hendobox** [comment]
Great. Thank you
