### ISSUE TITLE
New App Submission - Coinomi

### ISSUE THREAD

**Issue by veritaslogix** [WalletConnect/walletconnect-registry#419]
## App Logo (Required)

(Attach image here)
![intro_logo](https://user-images.githubusercontent.com/91297583/146683543-6a886937-f765-41f8-b66f-d67464a072a8.png)

## App Details (Required)

Type: Wallet
Name: Coinomi
Description: The blockchain wallet trusted by millions. Securely store, manage, and exchange Bitcoin, Ethereum, and more than 1,770 Tokens and Altcoins.

Homepage Url: https://www.coinomi.com/
Chains supported: Native support for over 125 blockchains, including: Bitcoin, Ethereum, Ripple, Bitcoin Cash, Bitcoin SV, Litecoin, Binance Coin, Monero, Tron, Ethereum Classic, Dash, NEM, ZCash, Doge, Decred, Bitcoin Gold, Algorand, MonaCoin, Horizen, DigiByte, Komodo, Verge, ZCoin, Aion, Stratis, Syscoin, PIVX, Vertcoin, Einsteinium, NavCoin, SmartCash, Peercoin, LBRY Credits, Viacoin, FIO and many more.

Versions supported:

## App Url (Required - at least one)

Browser Url:
iOS Url: https://itunes.apple.com/app/coinomi-wallet/id1333588809
Android Url: https://play.google.com/store/apps/details?id=com.coinomi.wallet
Mac Url: 
Windows Url: 
Linux Url: 

## Mobile Linking (Optional)

Deep Link: coinomi

Universal Link: https://coinomi.page.link
 
## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by veritaslogix** [comment]
Hello @pedrouid, I just submitted Coinomi in December 2021 to WalletConnect. However, I see that Coinomi was already submitted. The existing Coinomi submission lacks most of the information in my submission above. Please correct this by replacing the current Coinomi listing with my submission above. Thanks.

**Comment by chadyj** [comment]
Submitted to the cloud registry.
