### ISSUE TITLE
New App Submission - Boo!

### ISSUE THREAD

**Issue by bumoonio** [WalletConnect/walletconnect-registry#422]
## App Logo (Required)

![boo-logo-playstore](https://user-images.githubusercontent.com/84963053/147056478-a6ccb8ec-35da-4674-a215-07e341e23ec2.png)

## App Details (Required)

Type: Wallet
Name: Boo!
Description: Boo! stands for BUMooN Operation Orchestrator is a crypto wallet that fully operates under decentralize manner with no middleman interceptor, from basic wallet function to advance dApps interactions are accessible seamlessly trough Boo!, Boo! also connecting between real world activities and the blockchain world in order to collect attractive rewards and makes environment much better
Homepage Url: https://bumoon.io
Chains supported: BSC (BEP20)
Versions supported: 1.0.1

## App Url (Required - at least one)

Browser Url: 
iOS Url:  https://apps.apple.com/us/app/boo/id1593710564
Android Url: https://play.google.com/store/apps/details?id=io.bumoon.boo
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: https://boo.bumoon.io
Universal Link: https://boo.bumoon.io

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Boo!
Primary Color: #1d629b
Secondary Color: #0f88a5

**Comment by chadyj** [comment]
Added to the cloud registry.
