### ISSUE TITLE
New App Submission - Autonomy

### ISSUE THREAD

**Issue by thuyenBitmark** [WalletConnect/walletconnect-registry#424]
## App Logo (Required)
![512](https://user-images.githubusercontent.com/50816149/147336178-b807c4ed-4ba7-413a-b574-efa7238982bf.png)

## App Details (Required)

Type: Wallet and Dapp
Name: Autonomy
Description: Autonomy is the home for all your NFT art and other collectibles — a seamless, customizable way for you and others to experience your collection.
Homepage Url: https://bitmark.com/autonomy
Chains supported: Ethereum, Bitmark and Tezos
Versions supported:

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/autonomy-app/id1544022728
Android Url: https://play.google.com/store/apps/details?id=com.bitmark.autonomy_client
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: autonomy-wc
Universal Link: https://au.bitmark.com/apps/wc

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Already published.
