### ISSUE TITLE
New App Submission: Perpetual Protocol

### ISSUE THREAD

**Issue by yurenju** [WalletConnect/walletconnect-registry#427]
## App Logo (Required)

![Favicon](https://user-images.githubusercontent.com/22155/147428850-ec97dc03-c0f1-4b72-9cf0-4b80b3c22210.png)

## App Details (Required)

Type: Dapp
Name: Perpetual Protocol
Description: Decentralized Perpetual Contracts. On-chain DEX with highly efficient liquidity provisioning and up to 10x leverage for makers and takers.
Homepage Url: https://perp.com/
Chains supported: Optimism (chain id: 10)
Versions supported: 

## Metadata (Optional)

Short Name: Perp
Primary Color: #3CEAAA
Secondary Color: #03BCE4

there is geolocation blocking for certain counties, but it actually supports wallet connect
![image](https://user-images.githubusercontent.com/22155/147429473-dc4dfe48-e832-42ba-a092-af38c7cafc87.png)

**Comment by yurenju** [comment]
any update here?

**Comment by chadyj** [comment]
Added to the cloud registry.
