### ISSUE TITLE
New App Submission - CoinStats

### ISSUE THREAD

**Issue by arturdev** [WalletConnect/walletconnect-registry#428]
## App Logo (Required)

![Icon_83 5@2](https://user-images.githubusercontent.com/6263856/147569132-99c6ad7d-38b9-441c-a2cc-82f3b972f14c.png)

## App Details (Required)

Type: Wallet or Dapp
Name: CoinStats
Description: Manage Your Crypto and DeFi Portfolio From One Place
Homepage Url: https://coinstats.app/
Chains supported: polygon, binance smart chain, ethereum-mainnet
Versions supported:

## App Url (Required - at least one)

Browser Url: https://coinstats.app/
iOS Url: https://apps.apple.com/us/app/coin-stats-crypto-portfolio/id1247849330
Android Url:
Mac Url: https://apps.apple.com/us/app/coin-stats-crypto-tracker/id1498417304?mt=12
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: coinstats:
Universal Link: https://coinstats.app/walletconnect/

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: coinstats
Primary Color:  000000
Secondary Color: FF9332

**Comment by chadyj** [comment]
Submitted the the cloud registry
