### ISSUE TITLE
Dapper WalletNew App Submission

### ISSUE THREAD

**Issue by lucmarit** [WalletConnect/walletconnect-registry#43]
## App Logo (Required)
(Attach image here)
![image](https://user-images.githubusercontent.com/83096972/115933375-0ec4f700-a48f-11eb-8860-562de8e39d86.png)

## App Details (Required)
Type: Wallet or Dapp
Name: Ethereum Dapper Legacy Wallet
Homepage Url: https://www.meetdapper.com/
Chains supported: Ethereum

## App Url (Required - at least one)
Browser Url: https://www.meetdapper.com/
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Dapper doesn't support WalletConnect
