### ISSUE TITLE
New App Submission - Mask Network

### ISSUE THREAD

**Issue by sxiaojian88** [WalletConnect/walletconnect-registry#434]
## App Logo (Required)

<img width="400" alt="mask" src="https://user-images.githubusercontent.com/6863518/147734284-f34f2023-9259-4fd7-8444-a4e9a29c05f3.png">

## App Details (Required)

Type: Wallet and Dapp
Name: Mask Network
Description: The portal to the new, open internet.
Homepage Url: https://mask.io/
Chains supported: Ethereum, BSC, Polygon/Matic Network, Arbitrum, xDai
Versions supported: 2

## App Url (Required - at least one)

Browser Url: https://mask.io/download-links
iOS Url: https://mask.io/download-links
Android Url: https://mask.io/download-links
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: mask:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Mask
Primary Color: 
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
