### ISSUE TITLE
New App Submission - SafeMoon

### ISSUE THREAD

**Issue by ansafemoon** [WalletConnect/walletconnect-registry#436]
## App Logo (Required)

![180](https://user-images.githubusercontent.com/88300977/147736749-cf58522c-2b02-4c57-88a4-aa437bb84af5.png)

## App Details (Required)

Type: Wallet
Name: SafeMoon
Description:
Homepage Url: https://safemoon.net/
Chains supported: 1, 56
Versions supported: 1

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/safemoon/id1579735495
Android Url: https://play.google.com/store/apps/details?id=net.safemoon.androidwallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link: safemoon:
Universal Link: https://safemoon.net/

## Metadata (Optional)

Short Name: SafeMoon
Primary Color: rgb(0, 167, 157)
Secondary Color: rgb(11, 125, 118)

**Comment by ansafemoon** [comment]
@pedrouid Could you please help to review this? Thank you!

**Comment by chadyj** [comment]
Added to the cloud registry.
