### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by LIAMCODE2022** [WalletConnect/walletconnect-registry#440]
## App Logo (Required)
![logo@3x](https://user-images.githubusercontent.com/94336248/147932007-823376a6-c14c-4442-a50c-a25d67302e9e.png)

## App Details (Required)

Type: Wallet
Name: SafuLet
Description:
Homepage Url:
Chains supported: BSC ETH Polygon

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Closing, since no links were provided.
