### ISSUE TITLE
New App Submission - Forest Knight

### ISSUE THREAD

**Issue by Chrono-Games** [WalletConnect/walletconnect-registry#441]
## App Logo (Required)

![FK_App_Logo](https://user-images.githubusercontent.com/45699543/147964419-5996d6fe-bd3f-4c51-84b7-d5e97d77729e.png)

## App Details (Required)

Type: DAPP
Name: Forest Knight
Description: Free2Play Turn-Based-Strategy Game for Mobile
Homepage Url: https://www.forestknight.io/
Chains supported: Polygon, Ethereum
Versions supported: v1,v2

## App Url (Required - at least one)

Browser Url:
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=com.ChronoGames.Forest.Knight&hl=en&gl=US
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
