### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by mekarsemi** [WalletConnect/walletconnect-registry#442]
## App Logo (Required)

<img https://prodigichain.com/img/core-img/logo.png `/>`

## App Details (Required)

Type: Dapps
Name: digichain
Description: digichain wallet
Homepage Url: prodigichain.com
Chains supported: eth, bsc, bnb, polygon, matic
Versions supported: android dapps

## App Url (Required - at least one)

Browser Url: https://prodigichain.io/browser
iOS Url:
Android Url: https://play.google.com/store/apps/details?id=io.horizontalsystems.digichain
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: https://prodigichain.io/browser
Universal Link: https://prodigichain.io/browser

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: digichain wallet
Primary Color: blue
Secondary Color: black

**Comment by chadyj** [comment]
Closing since I couldn't determine how to use the dapp with WalletConnect.
