### ISSUE TITLE
New App Submission - Coingrig

### ISSUE THREAD

**Issue by florindumitru** [WalletConnect/walletconnect-registry#443]
## App Logo (Required)

![appstore](https://user-images.githubusercontent.com/1690803/148166876-1cfce3ff-e1d0-4da9-965c-d3fa01f64c00.png)

## App Details (Required)

Type: Wallet
Name: Coingrig
Description: A powerful crypto wallet for everyone. Private, secure and open source.
Homepage Url: https://coingrig.com
Chains supported: ETH, BSC, Polygon, Avalanche, Cronos

## App Url (Required - at least one)

Browser Url: https://coingrig.com
iOS Url: https://apps.apple.com/us/app/coingrig-crypto-btc-wallet/id1583464451
Android Url: https://play.google.com/store/apps/details?id=com.coingrig
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: coingrig://
Universal Link: https://link.coingrig.com

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Coingrig
Primary Color: 
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
