### ISSUE TITLE
New App Submission - Klever Wallet

### ISSUE THREAD

**Issue by ghsantos** [WalletConnect/walletconnect-registry#444]
## App Logo (Required)

![KleverIcon](https://user-images.githubusercontent.com/24828681/148294811-f6efe433-6b4b-4726-a60a-d31dd694c0ac.png)

## App Details (Required)

Type: Wallet
Name: Klever Wallet
Description: Klever app is a simple, powerful, smart and secure crypto wallet for Bitcoin (BTC), TRON (TRX), Ethereum (ETH), Binance (BNB) and other cryptocurrency assets serving over 2 million users from more than 190 countries worldwide. Klever is a decentralized p2p and self-custody wallet, putting the keys in the hands of our users. This means that you have total and full control of your private keys and that the Klever team cannot at any time or in any way access users’ funds or view your private keys.
Homepage Url: https://klever.finance/wallet/
Chains supported: ETH (1), BSC (56), Huobi (128), POLYGON (137)
Versions supported: V1.x

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/us/app/id1525584688
Android Url: https://play.google.com/store/apps/details?id=cash.klever.blockchain.wallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: kleverwallet:
Universal Link: https://klever.page.link

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Klever
Primary Color: rgb(220, 63, 137)
Secondary Color: rgb(144, 62, 221)

**Comment by chadyj** [comment]
Published.
