### ISSUE TITLE
Unlock 

### ISSUE THREAD

**Issue by julien51** [WalletConnect/walletconnect-registry#449]
## App Logo (Required)

[(Attach image here)
](https://github.com/unlock-protocol/unlock/blob/master/design/brand/1808-Unlock-Identity_Unlock-LogoMark-Circle.svg)

## App Details (Required)

Type: Dapp
Name: Unlock Protocol
Description: Unlock is a protocol for membership that lets creators, brands and communities monetize using memberships!
Homepage Url: https://unlock-protocol.com/
Chains supported: Ethereum, xDAI, Polygon, Optimism, BSC
Versions supported: 

## App Url (Required - at least one)

https://unlock-protocol.com/dashboard

iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Unlock Protocol
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
