### ISSUE TITLE
New App Submission - WHIM

### ISSUE THREAD

**Issue by vstupavsky** [WalletConnect/walletconnect-registry#451]
## App Logo (Required)

![WHIM Logo](https://user-images.githubusercontent.com/97696209/149387653-9c4218c5-851c-42a3-88d8-f6d2002d9ca2.png)

## App Details (Required)

Type: Dapp
Name: WHIM
Description: Imagine if you could change your space simply by changing what’s on your walls, without moving a single thing. We’re WHIM. An experience platform transforming the spaces where we live, work, chill and play.
Homepage Url: https://www.onawhim.com
Chains supported: Ethereum 
Versions supported: 1.x.x

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/app/whim/id1326895440
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Whim couldn't be tested because there was no signup.
Registry submissions should be publicly available. See https://walletconnect.com/registry/guidelines

Please resubmit when ready.
