### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by iliachesnokov** [WalletConnect/walletconnect-registry#452]
## App Logo (Required)

![logo](https://user-images.githubusercontent.com/4975005/149507867-e4c53ae4-9cb1-4ab2-a22b-5d0c523f378f.jpg)

## App Details (Required)

Type: Dapp
Name: Delta.theta
Description: Delta.theta Terminal
Homepage Url: https://deltatheta.tech
Chains supported: Ethereum, Binance Smart Chain
Versions supported: 1

## App Url (Required - at least one)

Browser Url: https://app.deltatheta.tech
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to cloud registry
