### ISSUE TITLE
New App Submission- Lead Wallet

### ISSUE THREAD

**Issue by Francisifegwu** [WalletConnect/walletconnect-registry#454]
## App Logo (Required)

![logo](https://user-images.githubusercontent.com/39567857/149650371-14d828e3-14ba-4b96-b5ec-dd2d9d1f1ed0.jpg)

## App Details (Required)

Type: Wallet
Name: Lead Wallet
Description: Lead Wallet is a multi-blockchain and multi-functional decentralized crypto wallet application with web3 DApp browser feature, NFT and custom fungible token wallet support, fiat-to-crypto swap support, Dex Aggregator feature, Multisender support, NFT and utility marketplace feature.
Homepage Url: https://leadwallet.io
Chains supported: Bitcoin, Ethereum, Celo, Polkadot, Polygon, BSC, Tezos, Stellar, Kusama, Dogecoin, RSK, Tron, Avalanche, Bitcoin Cash, Conflux, and other chains
Versions supported: mobile

## App Url (Required - at least one)

Browser Url: https://leadwallet.io/wallet
iOS Url: https://apps.apple.com/tt/app/lead-wallet/id1578704913
Android Url: https://play.google.com/store/apps/details?id=com.leadWallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: leadwallet://wallet-connect/
Universal Link: https://play.google.com/store/apps/details?id=com.leadWallet

## Desktop Linking (Optional)

Deep Link: leadwallet://wallet-connect/ 
Universal Link: https://play.google.com/store/apps/details?id=com.leadWallet

## Metadata (Optional)

Short Name: Lead
Primary Color: Pink (F90A88)
Secondary Color: Blue (3E2779)

**Comment by chadyj** [comment]
Added to the cloud registry

**Comment by Francisifegwu** [comment]
Thanks.
