### ISSUE TITLE
New App Submission (Snowball)

### ISSUE THREAD

**Issue by htarasenko** [WalletConnect/walletconnect-registry#458]
## App Logo (Required)
![App icon 60x60](https://user-images.githubusercontent.com/36541078/149834832-4e04885b-88c4-44b7-90fc-80b016402287.png)
![App icon 120x120](https://user-images.githubusercontent.com/36541078/149834879-117fee0d-20bc-49a7-ad28-8b8994370d11.png)
![App icon 400x400](https://user-images.githubusercontent.com/36541078/149834925-4c756474-5118-4166-9bc6-d65610e4040a.png)

## App Details (Required)

Type: Wallet
Name: Snowball
Description: https://snowball.money/
Homepage Url: https://snowball.money/
Chains supported: Ethereum, Binance, Polygon

## App Url (Required - at least one)

Browser Url: none
iOS Url: https://apps.apple.com/app/snowball-smart-defi-wallet/id1449662311
Android Url: https://play.google.com/store/apps/details?id=money.snowball.defi
Mac Url: none
Windows Url: none
Linux Url: none

## Mobile Linking (Optional)

Deep Link: app.snowball.exchange
Universal Link: app.snowball.exchange/app

## Desktop Linking (Optional)

Deep Link: none
Universal Link: none

## Metadata (Optional)

Short Name: Snowball
Primary Color: #292E39
Secondary Color: none

**Comment by chadyj** [comment]
Added to the cloud registry.
