### ISSUE TITLE
New App Submission – Edge

### ISSUE THREAD

**Issue by samholmes** [WalletConnect/walletconnect-registry#459]
## App Logo (Required)

![Edge App Logo](https://i.imgur.com/BI6fouR.png)

## App Details (Required)

Type: Wallet  
Name: Edge Wallet  
Description: Edge is a powerful and easy to use cryptocurrency wallet that allows users to easily control their own private keys with the familiarity and ease of mobile banking.  
Homepage Url: https://edge.app/  
Chains supported: Ethereum  
Versions supported: v1.0

## App Url (Required - at least one)

Browser Url:  
iOS Url: https://apps.apple.com/us/app/edge-bitcoin-wallet/id1344400091  
Android Url: https://play.google.com/store/apps/details?id=co.edgesecure.app  
Mac Url: (none)  
Windows Url: (none)  
Linux Url: (none)  

## Mobile Linking (Optional)

Deep Link: edge://wc  
Universal Link: https://deep.edge.app/wc  

## Desktop Linking (Optional)

Deep Link: (none)  
Universal Link: (none)  

## Metadata (Optional)

Short Name: Edge  
Primary Color: #66EDA8  
Secondary Color: #0D2145

**Comment by chadyj** [comment]
Added to cloud registry
