### ISSUE TITLE
New App Submission：Bycoin Wallet

### ISSUE THREAD

**Issue by MartinBTM** [WalletConnect/walletconnect-registry#460]
## App Logo (Required)

![](https://bytom.oss-cn-hongkong.aliyuncs.com/images/maz-tiny.png)

## App Details (Required)

Type: Wallet
Name: Bycoin
Description: Professional digital assets management platform
Homepage Url: https://bycoin.im
Chains supported: BTC ETH LTC DOT BTM

## App Url (Required - at least one)

Browser Url:
iOS Url: https://itunes.apple.com/us/app/bycoin/id1442183969?l=zh&ls=1&mt=8
Android Url: https://cdn.bystack.com/bycoin/apk/Bycoin.apk
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry
