### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by rdghostmann** [WalletConnect/walletconnect-registry#461]
## App Logo (Required)

https://www.defi-protocol.org/Defi%20%E2%80%93%20Protocol_files/Loader_img.png

## App Details (Required)

Type: Dapp
Name: DeFi-Protocol
Description: DeFi Protocol is a decentralized platform and network that blends Blockchain with DeFi, incorporating Blockchain aspects such as non-custodial management, micropools, rapid liquidity and decentralized governance. Each procedure must be completed in its entirely.
Homepage Url: https://www.defi-protocol.org/
Chains supported: Ethereum, Binance, CoinBase
Versions supported:

## App Url (Required - at least one)

Browser Url: https://www.defi-protocol.org/
iOS Url: https://www.defi-protocol.org/
Android Url:https://www.defi-protocol.org/
Mac Url: https://www.defi-protocol.org/
Windows Url:https://www.defi-protocol.org/
Linux Url: https://www.defi-protocol.org/

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Closing since https://www.defi-protocol.org is offline
