### ISSUE TITLE
New App Submission - Atomic Wallet

### ISSUE THREAD

**Issue by cyrudi** [WalletConnect/walletconnect-registry#462]
## App Logo (Required)

![atomic_wallet_logo_dark (2)](https://user-images.githubusercontent.com/80040507/150023061-a7f2bdb5-a479-443e-b572-a5ec9dfc026a.png)

## App Details (Required)

Type: Wallet
Name: Atomic Wallet
Description: Atomic Wallet is a decentralized Cryptocurrency wallet that supports more than 500 coins and tokens, providing simplicity, safety, and convenience for its users.
Homepage Url: [atomicwallet.io](https://atomicwallet.io/)
Chains supported: Bitcoin, Ethereum, Cardano, Polkadot, Dogecoin, Ripple, Litecoin, Ethereum Classic, Bitcoin Cash, Solana, Binance Chain, Binance Smart Chain, Tezos, Cosmos, Dash, Tron, Neo, Icon, Zilliqa, Algogrand, Komodo, Qtum, Vechain, Nem, Waves, Digibyte, Ark, Aeternity, Ycash, Smartcash, Groestlcoin, Bitcoin Gold, Bitcoin Diamond, Ontology, Zcash, Stellar, EOS, Hedera, Ravencoin.
Versions supported: 

## App Url (Required - at least one)

Browser Url: 
iOS Url: https://apps.apple.com/app/atomic-wallet/id1478257827
Android Url: https://play.google.com/store/apps/details?id=io.atomicwallet
Mac Url: https://atomicwallet.io/downloads
Windows Url: https://atomicwallet.io/downloads
Linux Url: https://atomicwallet.io/downloads

## Mobile Linking (Optional)

Deep Link: atomicwallet://wc
Universal Link: pay.atomicwallet.io
## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: Atomic
Primary Color: #1F2843
Secondary Color: #007aff

**Comment by chadyj** [comment]
Closing. Already published.
