### ISSUE TITLE
New App Submission - RuyiWallet

### ISSUE THREAD

**Issue by lxl518000** [WalletConnect/walletconnect-registry#463]
## App Logo (Required)

![bg_logo](https://user-images.githubusercontent.com/7520801/150297344-7e2ab884-5b67-4577-8fce-5e739508ade9.png)

## App Details (Required)

Type: Wallet
Name: RuyiWallet
Description: Dual-core wallet, support centralization/decentralization at the same time, one-click switching
Homepage Url:https://ruyiwallet.com/wallet.html
Chains supported:  Ethereum, Binance Smart Chain, Polygon (Matic),
Versions supported:

## App Url (Required - at least one)

Browser Url: https://ruyiwallet.com/wallet.html
iOS Url: 
Android Url: https://ruyiwallet.com/download.html
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Closing since this app isn't public/live yet.
See the guidelines https://walletconnect.com/registry/guidelines

Feel free to resubmit when launched.
