### ISSUE TITLE
New App Submission: KryptoGO Wallet

### ISSUE THREAD

**Issue by hitripod** [WalletConnect/walletconnect-registry#464]
## App Logo (Required)

![AppIcon-512](https://user-images.githubusercontent.com/550166/150320930-17360fb7-c204-423e-840a-6aa584a6c6d7.png)

## App Details (Required)

Type: Wallet
Name: KryptoGO Wallet
Description: The 1st decentralized DeFi Wallet with full compliance, allows you to invest in one click and reviews risk on the go. Unlock DeFi earning in your hand.

Homepage Url: https://kryptogo.com/wallet
Chains supported: Bitcoin, Ethereum, Polygon, Tron, Binance Smart Chain, Solana
Versions supported: v1.x, v2.0 coming in a few weeks

## App Url (Required - at least one)

Browser Url: https://kryptogo.com/wallet
iOS Url: https://apps.apple.com/il/app/kryptogo/id1593830910
Android Url: https://play.google.com/store/apps/details?id=com.kryptogo.walletapp
Mac Url: N/A
Windows Url: N/A
Linux Url: N/A

## Mobile Linking (Optional)

Deep Link: https://kryptogo.page.link
Universal Link: https://kryptogo.page.link

## Desktop Linking (Optional)

Deep Link: https://wallet.kryptogo.com
Universal Link: https://wallet.kryptogo.com

## Metadata (Optional)

Short Name: KryptoGO
Primary Color: #FFC211
Secondary Color: #001F58

**Comment by hitripod** [comment]
Android URL updated

**Comment by chadyj** [comment]
Added to the cloud registry.
