### ISSUE TITLE
New App Submission(Monkeep）

### ISSUE THREAD

**Issue by Monkeep** [WalletConnect/walletconnect-registry#467]
## App Logo (Required)
https://mine-resource-sz.oss-cn-shenzhen.aliyuncs.com/attachment/20220124/53721727c9ae48c1175c3ab6c1f22231.jpg

## App Details (Required)

Type: Wallet 
Name: Monkeep
Description:
Homepage Url:
Chains supported: Ethereum (ETH), including all ERC20 tokens; Bitcoin (BTC);Tron;DOGE
Versions supported:

## App Url (Required - at least one)

Browser Url:
iOS Url:https://financeh5.yunduocloud.cn/pages/download/download
Android Url:https://financeh5.yunduocloud.cn/pages/download/download
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link:
Universal Link:

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name:
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Closing.
Missing the description, and homepage.
You can resubmit to the cloud registry.
