### ISSUE TITLE
New App Submission: TK Finance

### ISSUE THREAD

**Issue by longndmta** [WalletConnect/walletconnect-registry#468]
## App Logo (Required)

![1024](https://user-images.githubusercontent.com/21114392/150813180-ef792362-1c51-4073-9630-ad9505d7374d.png)

## App Details (Required)

Type: Wallet
Name: TK Finance
Description: Entering the great Trustkeys Finance Ecosystem. Send crypto to friends directly in chat. Create Like, Share comment to Earn. Fast, safe, secure trading experience with Hybrid Change. Store all your digital assets securely in one place
Homepage Url: https://trustkeys.finance
Chains supported: Ethereum Mainnet, Ropsten, Binance Smart Chain Mainnet, Binance Smart Chain Testnet.
Versions supported: 1.0

## App Url (Required - at least one)

Browser Url:
iOS Url: https://apps.apple.com/vn/app/tk-finance/id1601968967
Android Url: Soon

## Mobile Linking (Optional)

Deep Link: tk://
Universal Link: https://trustkeys.finance

**Comment by chadyj** [comment]
Submitted to the cloud registry.
