### ISSUE TITLE
New App Submission - LOBSTR Wallet

### ISSUE THREAD

**Issue by let-it-snow** [WalletConnect/walletconnect-registry#469]
## App Logo (Required)

![Lbstr_500x500](https://user-images.githubusercontent.com/45386272/151199501-cb0d5551-2365-4993-b491-29f7f8392662.png)

## App Details (Required)

Type: Wallet
Name: LOBSTR Wallet
Description: LOBSTR is a leading platform for managing Stellar Lumens and other assets issued on the Stellar network.
Homepage Url: https://lobstr.co/
Chains supported: Stellar
Versions supported: 2.0

## App Url (Required - at least one)

Browser Url: https://lobstr.co/
iOS Url: https://apps.apple.com/us/app/lobstr-stellar-wallet/id1404357892
Android Url: https://play.google.com/store/apps/details?id=com.lobstr.client
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)

Deep Link: lobstr://wc
Universal Link: https://lobstr.co/uni/wc

## Desktop Linking (Optional)

Deep Link:
Universal Link:

## Metadata (Optional)

Short Name: LOBSTR
Primary Color:
Secondary Color:

**Comment by chadyj** [comment]
Added to the cloud registry.
