### ISSUE TITLE
New App Submission(Anybit)

### ISSUE THREAD

**Issue by Certificationwallet** [WalletConnect/walletconnect-registry#49]
## App Logo (Required)
![Anybit-logo](https://user-images.githubusercontent.com/79498968/116062776-cab43b00-a6b6-11eb-8092-abaf41c211f3.png)

## App Details (Required)
Type: Wallet
Name: Anybit
Homepage Url: https://www.anybit.io
Chains supported: Bitcoin, Ethereum, HECO, HX and more in future

## App Url (Required - at least one)
Browser Url:
iOS Url: https://www.anybit.io/#/download_ios
Android Url: https://anybit-1254113200.cos.ap-shanghai.myqcloud.com/release/anybit-3.0.2.apk
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by pedrouid** [comment]
Added on commit f86ec9ce158453802f5ab5bb19c86551b62204df
