### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by bchrvl** [WalletConnect/walletconnect-registry#5]
## App Logo (Required)
![Guarda Wallet Logo](https://guarda.com/assets/images/guarda-shield-logo.svg)

## App Details (Required)
Type: Wallet
Name: Guarda Wallet
Homepage Url: https://guarda.com/
Chains supported: ["eip155:1"]

## App Url (Required - at least one)
Browser Url: https://guarda.co/app/
iOS Url: https://apps.apple.com/app/apple-store/id1442083982
Android Url: https://play.google.com/store/apps/details?id=com.crypto.multiwallet
Mac Url: https://guarda.com/apps/Guarda-1.0.13.dmg
Windows Url: https://guarda.com/apps/Guarda_Setup-1.0.12-x64.exe
Linux Url: https://guarda.com/apps/Guarda_1.0.12_amd64.deb

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Guarda
Primary Color: #798ce5
Secondary Color: #ffffff

**Comment by pedrouid** [comment]
Do you actually support WalletConnect on all platforms (including Mac, Windows and Linux)???

**Comment by bchrvl** [comment]
It is available on iOS and Android. How can it be supported on Desktop apps?

**Comment by pedrouid** [comment]
For now the best option would be to add an input to paste the URI available from the "Copy to Clipboard" button which will match the same on the QR Code
