### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by YUKHYUNKI** [WalletConnect/walletconnect-registry#62]
<font class="papago-parent"><font class="papago-source" style="display:none;">## App Logo (Required)
</font>## 앱 로고(필수)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">(Attach image here)
</font>(여기 이미지 첨부)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">## App Details (Required)
</font>## 앱 세부 정보(필수)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Type: Wallet or Dapp
</font>유형: 지갑 또는 Dapp
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Name:
</font>이름:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Homepage Url:
</font>홈페이지 URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Chains supported:</font>지원되는 체인:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">## App Url (Required - at least one)
</font>## 앱 URL(필수 - 하나 이상)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Browser Url:
</font>브라우저 URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">iOS Url:
</font>iOS URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Android Url:
</font>Android URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Mac Url:
</font>Mac URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Windows Url:
</font>Windows URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Linux Url:
</font>Linux URL:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">## Mobile Linking (Optional)
</font>## 모바일 링크(옵션)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Deep Link:</font>딥 링크:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">Universal Link:</font>범용 링크:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">## Desktop Linking (Optional)
</font>## 데스크톱 연결(옵션)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Deep Link:</font>딥 링크:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">Universal Link:</font>범용 링크:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">## Metadata (Optional)
</font>## 메타데이터(옵션)
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Short Name:
</font>단축 이름:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Primary Color:
</font>기본 색상:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Secondary Color:
</font>보조 색상:
</font>

**Comment by YUKHYUNKI** [comment]
아임토큰 연동

**Comment by YUKHYUNKI** [comment]
핸드폰교체 기존지갑 연결

**Comment by pedrouid** [comment]
Hi there!

Could you please submit this in English?

Thanks in advance!

**Comment by chadyj** [comment]
Closing this since submissions should be in English. Please re-open or submit a new request with the required info.
