### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by mNizhurin** [WalletConnect/walletconnect-registry#86]
## App Logo (Required)
![unstop_1024](https://user-images.githubusercontent.com/1726387/117813690-3389de80-b285-11eb-9855-cf446b97cefb.png)

## App Details (Required)
Type: Wallet
Name: Unstoppable Wallet
Homepage Url: https://unstoppable.money/
Chains supported: ETH, BSC

## App Url (Required - at least one)
Browser Url:
iOS Url: https://apps.apple.com/app/bank-bitcoin-wallet/id1447619907
Android Url: https://play.google.com/store/apps/details?id=io.horizontalsystems.bankwallet
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: money.unstoppable
Universal Link: https://unstoppable.money/

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Unstoppable
Primary Color: #FFBE43

**Comment by pedrouid** [comment]
Updated on commit https://github.com/WalletConnect/walletconnect-registry/commit/1ed3f8fd9cb6c453632a8374b7c5ec839f3582f0
