### ISSUE TITLE
New App Submission - Valora

### ISSUE THREAD

**Issue by barbaraliau** [WalletConnect/walletconnect-registry#88]
## App Logo (Required)
![Valora](https://user-images.githubusercontent.com/10275927/117896922-dc810b00-b27e-11eb-97aa-2d85b24ce618.png)

## App Details (Required)
Type: Wallet
Name: Valora
Homepage Url: https://valoraapp.com/
Chains supported: [Celo](https://celo.org/)

## App Url (Required - at least one)
Browser Url: 
iOS Url: https://apps.apple.com/app/id1520414263
Android Url: https://play.google.com/store/apps/details?id=co.clabs.valora
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: celo://wallet/wc
Universal Link: https://valoraapp.com

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Valora
Primary Color: #42D689
Secondary Color: #FBCC5C
[](url)

**Comment by aslawson** [comment]
@chadyj is there anything further we need to do on our end for this?

**Comment by pedrouid** [comment]
Added on commit 7048a41
