### ISSUE TITLE
New App Submission

### ISSUE THREAD

**Issue by ivaneidel** [WalletConnect/walletconnect-registry#9]
## App Logo (Required)
![Logo](http://defiantapp.tech/wp-content/uploads/2020/11/icon.png)

## App Details (Required)
Type: Wallet
Name: Defiant
Homepage Url: https://defiantapp.tech/
Chains supported: ["eip155:1","eip155:42","eip155:30","eip155:31"]

## App Url (Required - at least one)
Browser Url:
iOS Url: *to be published*
Android Url: https://play.google.com/store/apps/details?id=ar.com.andinasmart.defiant
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link: defiantapp://
Universal Link: https://defiantapp.tech

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name: Defiant
Primary Color: #274A60
Secondary Color: #65ef9d

**Comment by pedrouid** [comment]
Added on commit: https://github.com/WalletConnect/walletconnect-registry/commit/230280fff3a5d683f098eed3a8df3780f50a8db4
