### ISSUE TITLE
New App Submission (Quiverx)

### ISSUE THREAD

**Issue by dharmveersinh** [WalletConnect/walletconnect-registry#95]
## App Logo (Required)
![Quiverx Logo](https://play-lh.googleusercontent.com/7CFG5inr0lZYixib0GPspdCUVzWeZxFhSq4XZVxKcAXtVm29Q_b1yj4y0LvjfVZeA3M=s180-rw)

## App Details (Required)
Type: Wallet
Name: QuiverX - Digital Wallet
Homepage Url: https://quiverx.io/app
Chains supported: Ethereum

## App Url (Required - at least one)
iOS Url: https://apps.apple.com/us/app/quiverx/id1558993212
Android Url: https://play.google.com/store/apps/details?id=com.quiverx.app

**Comment by dharmveersinh** [comment]
Hello @pedrouid,
When we are expecting to merge?

**Comment by pedrouid** [comment]
Added on commit 8959751cd60c00db72e84f2db872a693b3e132e4
