### ISSUE TITLE
New App Submission Poocoin.app

### ISSUE THREAD

**Issue by Pedro137BR** [WalletConnect/walletconnect-registry#99]
## App Logo (Required)
![poocoin512](https://user-images.githubusercontent.com/41971106/118363356-5d375400-b56a-11eb-82e4-9821ae0e2149.png)

## App Details (Required)
Type: Dapp
Name: Poocoin
Homepage Url: https://poocoin.app/
Chains supported: BNB

## App Url (Required - at least one)
Browser Url:
iOS Url:
Android Url:
Mac Url:
Windows Url:
Linux Url:

## Mobile Linking (Optional)
Deep Link:
Universal Link:

## Desktop Linking (Optional)
Deep Link:
Universal Link:

## Metadata (Optional)
Short Name:
Primary Color:
Secondary Color:

**Comment by Pedro137BR** [comment]
please all i want is to be able to manage it all on my pc

**Comment by chadyj** [comment]
@Pedro137BR I took a look at the app but wasn't able to test the WalletConnect integration. Can you make sure it works then resubmit? Also the app logo isn't available.
